Repository EveryUniv/student-council-homepage-backend, pull requests merged in 2023-05, with the labels that each got.

#328 NickName 중복 검증 및 UserInfo 정보 수정
  src/main/java/com/dku/council/domain/comment/repository/CommentRepository.java
  src/main/java/com/dku/council/domain/like/repository/LikePersistenceRepository.java
  src/main/java/com/dku/council/domain/post/repository/post/PostRepository.java
  src/main/java/com/dku/council/domain/user/model/dto/response/ResponseUserInfoDto.java
  src/main/java/com/dku/council/domain/user/service/UserService.java
  src/test/java/com/dku/council/domain/user/service/UserServiceTest.java
Labels: bug, fix

#339 티켓팅 및 댓글 수 버그 수정
  src/main/java/com/dku/council/domain/comment/repository/CommentRepository.java
  src/main/java/com/dku/council/domain/ticket/repository/TicketMemoryRepository.java
  src/main/java/com/dku/council/domain/ticket/repository/impl/TicketRedisRepository.java
  src/main/java/com/dku/council/domain/ticket/service/TicketService.java
  src/main/java/com/dku/council/domain/user/repository/UserRepository.java
  src/main/java/com/dku/council/domain/user/service/UserInfoCacheService.java
  src/main/java/com/dku/council/domain/user/service/UserService.java
  src/main/java/com/dku/council/global/config/redis/RedisKeys.java
  src/main/resources/templates/page/ticket/index.html
  src/test/java/com/dku/council/domain/comment/CommentRepositoryTest.java
  src/test/java/com/dku/council/domain/ticket/repository/impl/TicketRedisRepositoryTest.java
  src/test/java/com/dku/council/domain/ticket/service/TicketServiceTest.java
  src/test/java/com/dku/council/domain/user/service/UserInfoCacheServiceTest.java
  src/test/java/com/dku/council/domain/user/service/UserServiceTest.java
Labels: bug

#340 개발 서버에 배포
  src/main/java/com/dku/council/domain/comment/repository/CommentRepository.java
  src/main/java/com/dku/council/domain/post/repository/post/PostRepository.java
  src/main/java/com/dku/council/domain/ticket/repository/TicketMemoryRepository.java
  src/main/java/com/dku/council/domain/ticket/repository/impl/TicketRedisRepository.java
  src/main/java/com/dku/council/domain/ticket/service/TicketService.java
  src/main/java/com/dku/council/domain/user/model/dto/response/ResponseUserInfoDto.java
  src/main/java/com/dku/council/domain/user/repository/UserRepository.java
  src/main/java/com/dku/council/domain/user/service/UserInfoCacheService.java
  src/main/java/com/dku/council/domain/user/service/UserService.java
  src/main/java/com/dku/council/global/config/redis/RedisKeys.java
  src/main/resources/templates/page/ticket/index.html
  src/test/java/com/dku/council/domain/comment/CommentRepositoryTest.java
  src/test/java/com/dku/council/domain/ticket/repository/impl/TicketRedisRepositoryTest.java
  src/test/java/com/dku/council/domain/ticket/service/TicketServiceTest.java
  src/test/java/com/dku/council/domain/user/service/UserInfoCacheServiceTest.java
  src/test/java/com/dku/council/domain/user/service/UserServiceTest.java
Labels: deploy

#342 Integration 버그 수정
  src/main/java/com/dku/council/domain/admin/controller/PostPageController.java
  src/main/java/com/dku/council/domain/admin/service/PostPageService.java
  src/main/java/com/dku/council/domain/post/controller/ConferenceController.java
  src/main/java/com/dku/council/domain/post/controller/GeneralForumController.java
  src/main/java/com/dku/council/domain/post/controller/NewsController.java
  src/main/java/com/dku/council/domain/post/controller/PetitionController.java
  src/main/java/com/dku/council/domain/post/controller/RuleController.java
  src/main/java/com/dku/council/domain/post/controller/VocController.java
  src/main/java/com/dku/council/domain/post/model/dto/list/SummarizedGenericPostDto.java
  src/main/java/com/dku/council/domain/post/repository/post/GeneralForumRepository.java
  src/main/java/com/dku/council/domain/post/repository/post/PetitionRepository.java
  src/main/java/com/dku/council/domain/post/repository/post/PostRepository.java
  src/main/java/com/dku/council/domain/post/service/post/ConferenceService.java
  src/main/java/com/dku/council/domain/post/service/post/GeneralForumService.java
  src/main/java/com/dku/council/domain/post/service/post/GenericPostService.java
  src/main/java/com/dku/council/domain/post/service/post/NewsService.java
  src/main/java/com/dku/council/domain/post/service/post/PetitionService.java
  src/main/java/com/dku/council/domain/post/service/post/RuleService.java
  src/main/java/com/dku/council/domain/post/service/post/VocService.java
  src/main/java/com/dku/council/domain/ticket/service/TicketService.java
  src/main/java/com/dku/council/domain/ticket/service/TicketVerifyService.java
  src/main/java/com/dku/council/domain/user/controller/UserController.java
  src/main/java/com/dku/council/domain/user/model/entity/User.java
  src/main/java/com/dku/council/domain/user/service/DKUAuthService.java
  src/main/java/com/dku/council/domain/user/service/MyPostService.java
  src/main/java/com/dku/council/domain/user/service/UserFindService.java
  src/main/java/com/dku/council/domain/user/service/UserInfoService.java
  src/main/java/com/dku/council/domain/user/service/UserService.java
  src/main/java/com/dku/council/infra/naver/service/CaptchaService.java
  src/test/java/com/dku/council/domain/post/repository/PetitionRepositoryTest.java
  src/test/java/com/dku/council/domain/post/repository/post/GeneralForumRepositoryTest.java
  src/test/java/com/dku/council/domain/post/repository/post/PostRepositoryTest.java
  src/test/java/com/dku/council/domain/post/service/GeneralForumServiceTest.java
  src/test/java/com/dku/council/domain/post/service/GenericPostServiceTest.java
  src/test/java/com/dku/council/domain/post/service/PetitionServiceTest.java
  src/test/java/com/dku/council/domain/post/service/post/GeneralForumServiceTest.java
  src/test/java/com/dku/council/domain/ticket/service/TicketServiceTest.java
  src/test/java/com/dku/council/domain/ticket/service/TicketVerifyServiceTest.java
  src/test/java/com/dku/council/domain/user/service/DKUAuthServiceTest.java
  src/test/java/com/dku/council/domain/user/service/UserFindServiceTest.java
  src/test/java/com/dku/council/domain/user/service/UserInfoServiceTest.java
  src/test/java/com/dku/council/domain/user/service/UserServiceTest.java
  src/test/java/com/dku/council/infra/dku/scrapper/actual/ActualDkuStudentServiceTest.java
Labels: bug, update

#343 개발 서버에 배포
  src/main/java/com/dku/council/domain/admin/controller/PostPageController.java
  src/main/java/com/dku/council/domain/admin/service/PostPageService.java
  src/main/java/com/dku/council/domain/post/controller/ConferenceController.java
  src/main/java/com/dku/council/domain/post/controller/GeneralForumController.java
  src/main/java/com/dku/council/domain/post/controller/NewsController.java
  src/main/java/com/dku/council/domain/post/controller/PetitionController.java
  src/main/java/com/dku/council/domain/post/controller/RuleController.java
  src/main/java/com/dku/council/domain/post/controller/VocController.java
  src/main/java/com/dku/council/domain/post/model/dto/list/SummarizedGenericPostDto.java
  src/main/java/com/dku/council/domain/post/repository/post/GeneralForumRepository.java
  src/main/java/com/dku/council/domain/post/repository/post/PetitionRepository.java
  src/main/java/com/dku/council/domain/post/repository/post/PostRepository.java
  src/main/java/com/dku/council/domain/post/service/post/ConferenceService.java
  src/main/java/com/dku/council/domain/post/service/post/GeneralForumService.java
  src/main/java/com/dku/council/domain/post/service/post/GenericPostService.java
  src/main/java/com/dku/council/domain/post/service/post/NewsService.java
  src/main/java/com/dku/council/domain/post/service/post/PetitionService.java
  src/main/java/com/dku/council/domain/post/service/post/RuleService.java
  src/main/java/com/dku/council/domain/post/service/post/VocService.java
  src/main/java/com/dku/council/domain/ticket/service/TicketService.java
  src/main/java/com/dku/council/domain/ticket/service/TicketVerifyService.java
  src/main/java/com/dku/council/domain/user/controller/UserController.java
  src/main/java/com/dku/council/domain/user/model/entity/User.java
  src/main/java/com/dku/council/domain/user/service/DKUAuthService.java
  src/main/java/com/dku/council/domain/user/service/MyPostService.java
  src/main/java/com/dku/council/domain/user/service/UserFindService.java
  src/main/java/com/dku/council/domain/user/service/UserInfoService.java
  src/main/java/com/dku/council/domain/user/service/UserService.java
  src/main/java/com/dku/council/infra/naver/service/CaptchaService.java
  src/test/java/com/dku/council/domain/post/repository/PetitionRepositoryTest.java
  src/test/java/com/dku/council/domain/post/repository/post/GeneralForumRepositoryTest.java
  src/test/java/com/dku/council/domain/post/repository/post/PostRepositoryTest.java
  src/test/java/com/dku/council/domain/post/service/GeneralForumServiceTest.java
  src/test/java/com/dku/council/domain/post/service/GenericPostServiceTest.java
  src/test/java/com/dku/council/domain/post/service/PetitionServiceTest.java
  src/test/java/com/dku/council/domain/post/service/post/GeneralForumServiceTest.java
  src/test/java/com/dku/council/domain/ticket/service/TicketServiceTest.java
  src/test/java/com/dku/council/domain/ticket/service/TicketVerifyServiceTest.java
  src/test/java/com/dku/council/domain/user/service/DKUAuthServiceTest.java
  src/test/java/com/dku/council/domain/user/service/UserFindServiceTest.java
  src/test/java/com/dku/council/domain/user/service/UserInfoServiceTest.java
  src/test/java/com/dku/council/domain/user/service/UserServiceTest.java
  src/test/java/com/dku/council/infra/dku/scrapper/actual/ActualDkuStudentServiceTest.java
Labels: deploy

#344 운영 서버에 베포
  src/main/java/com/dku/council/domain/admin/controller/PostPageController.java
  src/main/java/com/dku/council/domain/admin/service/PostPageService.java
  src/main/java/com/dku/council/domain/post/controller/ConferenceController.java
  src/main/java/com/dku/council/domain/post/controller/GeneralForumController.java
  src/main/java/com/dku/council/domain/post/controller/NewsController.java
  src/main/java/com/dku/council/domain/post/controller/PetitionController.java
  src/main/java/com/dku/council/domain/post/controller/RuleController.java
  src/main/java/com/dku/council/domain/post/controller/VocController.java
  src/main/java/com/dku/council/domain/post/model/dto/list/SummarizedGenericPostDto.java
  src/main/java/com/dku/council/domain/post/repository/post/GeneralForumRepository.java
  src/main/java/com/dku/council/domain/post/repository/post/PetitionRepository.java
  src/main/java/com/dku/council/domain/post/repository/post/PostRepository.java
  src/main/java/com/dku/council/domain/post/service/post/ConferenceService.java
  src/main/java/com/dku/council/domain/post/service/post/GeneralForumService.java
  src/main/java/com/dku/council/domain/post/service/post/GenericPostService.java
  src/main/java/com/dku/council/domain/post/service/post/NewsService.java
  src/main/java/com/dku/council/domain/post/service/post/PetitionService.java
  src/main/java/com/dku/council/domain/post/service/post/RuleService.java
  src/main/java/com/dku/council/domain/post/service/post/VocService.java
  src/main/java/com/dku/council/domain/ticket/service/TicketService.java
  src/main/java/com/dku/council/domain/ticket/service/TicketVerifyService.java
  src/main/java/com/dku/council/domain/user/controller/UserController.java
  src/main/java/com/dku/council/domain/user/model/entity/User.java
  src/main/java/com/dku/council/domain/user/service/DKUAuthService.java
  src/main/java/com/dku/council/domain/user/service/MyPostService.java
  src/main/java/com/dku/council/domain/user/service/UserFindService.java
  src/main/java/com/dku/council/domain/user/service/UserInfoService.java
  src/main/java/com/dku/council/domain/user/service/UserService.java
  src/main/java/com/dku/council/infra/naver/service/CaptchaService.java
  src/test/java/com/dku/council/domain/post/repository/PetitionRepositoryTest.java
  src/test/java/com/dku/council/domain/post/repository/post/GeneralForumRepositoryTest.java
  src/test/java/com/dku/council/domain/post/repository/post/PostRepositoryTest.java
  src/test/java/com/dku/council/domain/post/service/GeneralForumServiceTest.java
  src/test/java/com/dku/council/domain/post/service/GenericPostServiceTest.java
  src/test/java/com/dku/council/domain/post/service/PetitionServiceTest.java
  src/test/java/com/dku/council/domain/post/service/post/GeneralForumServiceTest.java
  src/test/java/com/dku/council/domain/ticket/service/TicketServiceTest.java
  src/test/java/com/dku/council/domain/ticket/service/TicketVerifyServiceTest.java
  src/test/java/com/dku/council/domain/user/service/DKUAuthServiceTest.java
  src/test/java/com/dku/council/domain/user/service/UserFindServiceTest.java
  src/test/java/com/dku/council/domain/user/service/UserInfoServiceTest.java
  src/test/java/com/dku/council/domain/user/service/UserServiceTest.java
  src/test/java/com/dku/council/infra/dku/scrapper/actual/ActualDkuStudentServiceTest.java
Labels: deploy

#345 일부 로직 수정
  src/main/java/com/dku/council/domain/like/repository/LikePersistenceRepository.java
  src/main/java/com/dku/council/domain/like/service/impl/CachedLikeServiceImpl.java
  src/main/java/com/dku/council/domain/user/service/UserFindService.java
  src/main/resources/messages.properties
  src/main/resources/messages_en_US.properties
  src/test/java/com/dku/council/domain/like/service/CachedLikeServiceImplTest.java
Labels: bug

#346 개발 서버에 배포
  src/main/java/com/dku/council/domain/like/repository/LikePersistenceRepository.java
  src/main/java/com/dku/council/domain/like/service/impl/CachedLikeServiceImpl.java
  src/main/java/com/dku/council/domain/user/service/UserFindService.java
  src/main/resources/messages.properties
  src/main/resources/messages_en_US.properties
  src/test/java/com/dku/council/domain/like/service/CachedLikeServiceImplTest.java
Labels: deploy

#349 회원 탈퇴 및 티켓팅 메시지 수정
  src/main/java/com/dku/council/domain/admin/service/UserPageService.java
  src/main/java/com/dku/council/domain/batch/UserWithdrawScheduler.java
  src/main/java/com/dku/council/domain/comment/model/entity/Comment.java
  src/main/java/com/dku/council/domain/comment/repository/CommentRepository.java
  src/main/java/com/dku/council/domain/comment/service/CommentService.java
  src/main/java/com/dku/council/domain/post/model/entity/Post.java
  src/main/java/com/dku/council/domain/post/model/entity/posttype/Conference.java
  src/main/java/com/dku/council/domain/post/model/entity/posttype/News.java
  src/main/java/com/dku/council/domain/post/model/entity/posttype/Petition.java
  src/main/java/com/dku/council/domain/post/model/entity/posttype/Rule.java
  src/main/java/com/dku/council/domain/post/repository/post/PostRepository.java
  src/main/java/com/dku/council/domain/post/service/post/GenericPostService.java
  src/main/java/com/dku/council/domain/ticket/exception/AfterTicketPeriodException.java
  src/main/java/com/dku/council/domain/ticket/exception/BeforeTicketPeriodException.java
  src/main/java/com/dku/council/domain/ticket/exception/InvalidTicketPeriodException.java
  src/main/java/com/dku/council/domain/ticket/service/TicketService.java
  src/main/java/com/dku/council/domain/user/controller/UserController.java
  src/main/java/com/dku/council/domain/user/model/UserStatus.java
  src/main/java/com/dku/council/domain/user/model/entity/User.java
  src/main/java/com/dku/council/domain/user/repository/UserRepository.java
  src/main/java/com/dku/council/domain/user/service/SignupService.java
  src/main/java/com/dku/council/domain/user/service/UserService.java
  src/main/java/com/dku/council/domain/user/service/UserWithdrawService.java
  src/main/resources/errors.properties
  src/main/resources/errors_en_US.properties
  src/test/java/com/dku/council/domain/ticket/service/TicketServiceTest.java
  src/test/java/com/dku/council/domain/user/service/UserFindServiceTest.java
  src/test/java/com/dku/council/mock/UserInfoMock.java
  src/test/java/com/dku/council/mock/UserMock.java
  src/test/resources/errors.properties
  src/test/resources/errors_en_US.properties
Labels: feat, update

#350 개발 서버에 배포
  src/main/java/com/dku/council/domain/admin/service/UserPageService.java
  src/main/java/com/dku/council/domain/batch/UserWithdrawScheduler.java
  src/main/java/com/dku/council/domain/comment/model/entity/Comment.java
  src/main/java/com/dku/council/domain/comment/repository/CommentRepository.java
  src/main/java/com/dku/council/domain/comment/service/CommentService.java
  src/main/java/com/dku/council/domain/post/model/entity/Post.java
  src/main/java/com/dku/council/domain/post/model/entity/posttype/Conference.java
  src/main/java/com/dku/council/domain/post/model/entity/posttype/News.java
  src/main/java/com/dku/council/domain/post/model/entity/posttype/Petition.java
  src/main/java/com/dku/council/domain/post/model/entity/posttype/Rule.java
  src/main/java/com/dku/council/domain/post/repository/post/PostRepository.java
  src/main/java/com/dku/council/domain/post/service/post/GenericPostService.java
  src/main/java/com/dku/council/domain/ticket/exception/AfterTicketPeriodException.java
  src/main/java/com/dku/council/domain/ticket/exception/BeforeTicketPeriodException.java
  src/main/java/com/dku/council/domain/ticket/exception/InvalidTicketPeriodException.java
  src/main/java/com/dku/council/domain/ticket/service/TicketService.java
  src/main/java/com/dku/council/domain/user/controller/UserController.java
  src/main/java/com/dku/council/domain/user/model/UserStatus.java
  src/main/java/com/dku/council/domain/user/model/entity/User.java
  src/main/java/com/dku/council/domain/user/repository/UserRepository.java
  src/main/java/com/dku/council/domain/user/service/SignupService.java
  src/main/java/com/dku/council/domain/user/service/UserService.java
  src/main/java/com/dku/council/domain/user/service/UserWithdrawService.java
  src/main/resources/errors.properties
  src/main/resources/errors_en_US.properties
  src/test/java/com/dku/council/domain/ticket/service/TicketServiceTest.java
  src/test/java/com/dku/council/domain/user/service/UserFindServiceTest.java
  src/test/java/com/dku/council/mock/UserInfoMock.java
  src/test/java/com/dku/council/mock/UserMock.java
  src/test/resources/errors.properties
  src/test/resources/errors_en_US.properties
Labels: deploy

#351 운영 서버에 배포
  src/main/java/com/dku/council/domain/admin/service/UserPageService.java
  src/main/java/com/dku/council/domain/batch/UserWithdrawScheduler.java
  src/main/java/com/dku/council/domain/comment/model/entity/Comment.java
  src/main/java/com/dku/council/domain/comment/repository/CommentRepository.java
  src/main/java/com/dku/council/domain/comment/service/CommentService.java
  src/main/java/com/dku/council/domain/like/repository/LikePersistenceRepository.java
  src/main/java/com/dku/council/domain/like/service/impl/CachedLikeServiceImpl.java
  src/main/java/com/dku/council/domain/post/model/entity/Post.java
  src/main/java/com/dku/council/domain/post/model/entity/posttype/Conference.java
  src/main/java/com/dku/council/domain/post/model/entity/posttype/News.java
  src/main/java/com/dku/council/domain/post/model/entity/posttype/Petition.java
  src/main/java/com/dku/council/domain/post/model/entity/posttype/Rule.java
  src/main/java/com/dku/council/domain/post/repository/post/PostRepository.java
  src/main/java/com/dku/council/domain/post/service/post/GenericPostService.java
  src/main/java/com/dku/council/domain/ticket/exception/AfterTicketPeriodException.java
  src/main/java/com/dku/council/domain/ticket/exception/BeforeTicketPeriodException.java
  src/main/java/com/dku/council/domain/ticket/exception/InvalidTicketPeriodException.java
  src/main/java/com/dku/council/domain/ticket/service/TicketService.java
  src/main/java/com/dku/council/domain/user/controller/UserController.java
  src/main/java/com/dku/council/domain/user/model/UserStatus.java
  src/main/java/com/dku/council/domain/user/model/entity/User.java
  src/main/java/com/dku/council/domain/user/repository/UserRepository.java
  src/main/java/com/dku/council/domain/user/service/SignupService.java
  src/main/java/com/dku/council/domain/user/service/UserFindService.java
  src/main/java/com/dku/council/domain/user/service/UserService.java
  src/main/java/com/dku/council/domain/user/service/UserWithdrawService.java
  src/main/resources/errors.properties
  src/main/resources/errors_en_US.properties
  src/main/resources/messages.properties
  src/main/resources/messages_en_US.properties
  src/test/java/com/dku/council/domain/like/service/CachedLikeServiceImplTest.java
  src/test/java/com/dku/council/domain/ticket/service/TicketServiceTest.java
  src/test/java/com/dku/council/domain/user/service/UserFindServiceTest.java
  src/test/java/com/dku/council/mock/UserInfoMock.java
  src/test/java/com/dku/council/mock/UserMock.java
  src/test/resources/errors.properties
  src/test/resources/errors_en_US.properties
Labels: deploy

#354 개발 서버에 배포
  Dockerfile
  src/main/java/com/dku/council/global/config/WebConfig.java
Labels: deploy

#355 운영 서버에 배포
  Dockerfile
  src/main/java/com/dku/council/global/config/WebConfig.java
Labels: deploy

#356 버스 timeout 추가
  src/main/java/com/dku/council/domain/bus/model/dto/ResponseBusArrivalDto.java
  src/main/java/com/dku/council/domain/ticket/controller/TicketController.java
  src/main/java/com/dku/council/domain/user/service/UserInfoService.java
  src/main/java/com/dku/council/global/config/jackson/JacksonDateTimeFormatter.java
  src/main/java/com/dku/council/global/config/webclient/WebClientConfig.java
  src/test/java/com/dku/council/domain/user/service/UserInfoServiceTest.java
Labels: bug

#357 개발 서버에 배포
  src/main/java/com/dku/council/domain/bus/model/dto/ResponseBusArrivalDto.java
  src/main/java/com/dku/council/domain/ticket/controller/TicketController.java
  src/main/java/com/dku/council/domain/user/service/UserInfoService.java
  src/main/java/com/dku/council/global/config/jackson/JacksonDateTimeFormatter.java
  src/main/java/com/dku/council/global/config/webclient/WebClientConfig.java
  src/test/java/com/dku/council/domain/user/service/UserInfoServiceTest.java
Labels: deploy

#358 운영 서버에 배포
  src/main/java/com/dku/council/domain/bus/model/dto/ResponseBusArrivalDto.java
  src/main/java/com/dku/council/domain/ticket/controller/TicketController.java
  src/main/java/com/dku/council/domain/user/service/UserInfoService.java
  src/main/java/com/dku/council/global/config/jackson/JacksonDateTimeFormatter.java
  src/main/java/com/dku/council/global/config/webclient/WebClientConfig.java
  src/test/java/com/dku/council/domain/user/service/UserInfoServiceTest.java
Labels: deploy

#360 야간수업 시간 조정
  src/main/java/com/dku/council/infra/dku/scrapper/DkuLectureService.java
  src/test/java/com/dku/council/infra/dku/scrapper/DkuLectureServiceTest.java
  src/test/resources/mockdata/dku/lecture-major-response.html
  src/test/resources/mockdata/dku/lecture-subject-response.html
Labels: bug

#361 개발 서버에 배포
  src/main/java/com/dku/council/infra/dku/scrapper/DkuLectureService.java
  src/test/java/com/dku/council/infra/dku/scrapper/DkuLectureServiceTest.java
  src/test/resources/mockdata/dku/lecture-major-response.html
  src/test/resources/mockdata/dku/lecture-subject-response.html
Labels: deploy

#362 버스 time 버그
  src/main/java/com/dku/council/infra/dku/model/Subject.java
  src/main/java/com/dku/council/infra/dku/scrapper/DkuLectureService.java
  src/test/java/com/dku/council/infra/dku/scrapper/DkuLectureServiceTest.java
  src/test/resources/mockdata/dku/lecture-major-response.html
Labels: bug

#363 개발 서버에 배포
  src/main/java/com/dku/council/infra/dku/model/Subject.java
  src/main/java/com/dku/council/infra/dku/scrapper/DkuLectureService.java
  src/test/java/com/dku/council/infra/dku/scrapper/DkuLectureServiceTest.java
  src/test/resources/mockdata/dku/lecture-major-response.html
Labels: deploy

#365 CORS 설정 다중화
  src/main/java/com/dku/council/global/config/WebConfig.java
  src/test/java/com/dku/council/global/config/WebConfigTest.java
Labels: chore

#366 개발 서버에 배포
  src/main/java/com/dku/council/global/config/WebConfig.java
  src/test/java/com/dku/council/global/config/WebConfigTest.java
Labels: deploy

#364 운영 서버에 배포
  src/main/java/com/dku/council/global/config/WebConfig.java
  src/main/java/com/dku/council/infra/dku/model/Subject.java
  src/main/java/com/dku/council/infra/dku/scrapper/DkuLectureService.java
  src/test/java/com/dku/council/global/config/WebConfigTest.java
  src/test/java/com/dku/council/infra/dku/scrapper/DkuLectureServiceTest.java
  src/test/resources/mockdata/dku/lecture-major-response.html
  src/test/resources/mockdata/dku/lecture-subject-response.html
Labels: deploy

#367 SMS 메시지 수정
  src/main/resources/messages_en_US.properties
Labels: bug

#368 운영 서버에 배포
  src/main/resources/messages_en_US.properties
Labels: bug

#369 log 설정
  .gitignore
  src/main/resources/logback-with-file-log.xml
Labels: chore

#370 운영 서버에 배포
  .gitignore
  src/main/resources/logback-with-file-log.xml
Labels: chore

#373 개발 서버에 배포
  .github/workflows/dev_cd.yml
  .github/workflows/prod_cd.yml
  .gitignore
  src/main/resources/logback-with-file-log.xml
  src/main/resources/messages_en_US.properties
Labels: deploy

#374 URL encode param
  src/main/java/com/dku/council/infra/dku/scrapper/DkuAuthenticationService.java
  src/test/java/com/dku/council/domain/ticket/service/TicketConcurrencyTest.java
Labels: bug

#375 운영 서버에 배포
  src/main/java/com/dku/council/infra/dku/scrapper/DkuAuthenticationService.java
  src/test/java/com/dku/council/domain/ticket/service/TicketConcurrencyTest.java
Labels: deploy

#376 청원 만료시 동의 불가하도록 수정
  src/main/java/com/dku/council/domain/post/exception/ExpiredPetitionException.java
  src/main/java/com/dku/council/domain/post/service/post/PetitionService.java
  src/main/java/com/dku/council/infra/dku/scrapper/DkuAuthenticationService.java
  src/main/resources/errors.properties
  src/main/resources/errors_en_US.properties
Labels: bug

#378 개발 서버에 배포
  src/main/java/com/dku/council/domain/post/exception/ExpiredPetitionException.java
  src/main/java/com/dku/council/domain/post/service/post/PetitionService.java
  src/main/java/com/dku/council/domain/ticket/model/dto/response/ResponseManagerTicketDto.java
  src/main/java/com/dku/council/domain/ticket/service/TicketVerifyService.java
  src/main/java/com/dku/council/infra/dku/scrapper/DkuAuthenticationService.java
  src/main/resources/errors.properties
  src/main/resources/errors_en_US.properties
  src/main/resources/messages.properties
  src/main/resources/messages_en_US.properties
  src/test/java/com/dku/council/domain/ticket/controller/TicketVerifyControllerTest.java
  src/test/java/com/dku/council/domain/ticket/service/TicketConcurrencyTest.java
  src/test/java/com/dku/council/domain/ticket/service/TicketVerifyServiceTest.java
Labels: deploy

#377 운영 서버에 배포
  src/main/java/com/dku/council/domain/post/exception/ExpiredPetitionException.java
  src/main/java/com/dku/council/domain/post/service/post/PetitionService.java
  src/main/java/com/dku/council/domain/ticket/model/dto/response/ResponseManagerTicketDto.java
  src/main/java/com/dku/council/domain/ticket/service/TicketVerifyService.java
  src/main/java/com/dku/council/infra/dku/scrapper/DkuAuthenticationService.java
  src/main/resources/errors.properties
  src/main/resources/errors_en_US.properties
  src/main/resources/messages.properties
  src/main/resources/messages_en_US.properties
  src/test/java/com/dku/council/domain/ticket/controller/TicketVerifyControllerTest.java
  src/test/java/com/dku/council/domain/ticket/service/TicketVerifyServiceTest.java
Labels: deploy

#386 무중단 배포
  .github/workflows/dev_cd.yml
  .github/workflows/prod_cd.yml
  src/main/java/com/dku/council/global/auth/role/UserAuthNames.java
Labels: chore

#387 무중단 배포 테스트
  .github/workflows/dev_cd.yml
  .github/workflows/prod_cd.yml
  src/main/java/com/dku/council/global/auth/role/UserAuthNames.java
Labels: deploy

#384 신고기능 리팩토링
  src/main/java/com/dku/council/domain/comment/model/entity/Comment.java
  src/main/java/com/dku/council/domain/comment/model/entity/CommentLog.java
  src/main/java/com/dku/council/domain/post/model/dto/request/RequestCreateReportDto.java
  src/main/java/com/dku/council/domain/post/model/entity/Post.java
  src/main/java/com/dku/council/domain/post/service/ViewCountService.java
  src/main/java/com/dku/council/domain/report/controller/ReportController.java
  src/main/java/com/dku/council/domain/report/model/dto/list/ResponseReportCategoryDto.java
  src/main/java/com/dku/council/domain/report/model/dto/response/ResponseSingleReportedPostDto.java
  src/main/java/com/dku/council/domain/report/model/dto/response/SummarizedReportedPostDto.java
  src/main/java/com/dku/council/domain/report/model/entity/Report.java
  src/main/java/com/dku/council/domain/report/model/entity/ReportCategory.java
  src/main/java/com/dku/council/domain/report/repository/ReportRepository.java
  src/main/java/com/dku/council/domain/report/service/ReportService.java
  src/main/java/com/dku/council/infra/nhn/service/SMSService.java
  src/test/java/com/dku/council/domain/report/repository/ReportRepositoryTest.java
Labels: refactor

#388 개발 서버에 배포
  src/main/java/com/dku/council/domain/comment/model/entity/Comment.java
  src/main/java/com/dku/council/domain/comment/model/entity/CommentLog.java
  src/main/java/com/dku/council/domain/post/model/dto/request/RequestCreateReportDto.java
  src/main/java/com/dku/council/domain/post/model/entity/Post.java
  src/main/java/com/dku/council/domain/post/service/ViewCountService.java
  src/main/java/com/dku/council/domain/report/controller/ReportController.java
  src/main/java/com/dku/council/domain/report/model/dto/list/ResponseReportCategoryDto.java
  src/main/java/com/dku/council/domain/report/model/dto/response/ResponseSingleReportedPostDto.java
  src/main/java/com/dku/council/domain/report/model/dto/response/SummarizedReportedPostDto.java
  src/main/java/com/dku/council/domain/report/model/entity/Report.java
  src/main/java/com/dku/council/domain/report/model/entity/ReportCategory.java
  src/main/java/com/dku/council/domain/report/repository/ReportRepository.java
  src/main/java/com/dku/council/domain/report/service/ReportService.java
  src/main/java/com/dku/council/infra/nhn/service/SMSService.java
  src/test/java/com/dku/council/domain/report/repository/ReportRepositoryTest.java
Labels: deploy

#389 운영 서버에 배포
  .github/workflows/dev_cd.yml
  .github/workflows/prod_cd.yml
  src/main/java/com/dku/council/domain/comment/model/entity/Comment.java
  src/main/java/com/dku/council/domain/comment/model/entity/CommentLog.java
  src/main/java/com/dku/council/domain/post/model/dto/request/RequestCreateReportDto.java
  src/main/java/com/dku/council/domain/post/model/entity/Post.java
  src/main/java/com/dku/council/domain/post/service/ViewCountService.java
  src/main/java/com/dku/council/domain/report/controller/ReportController.java
  src/main/java/com/dku/council/domain/report/model/dto/list/ResponseReportCategoryDto.java
  src/main/java/com/dku/council/domain/report/model/dto/response/ResponseSingleReportedPostDto.java
  src/main/java/com/dku/council/domain/report/model/dto/response/SummarizedReportedPostDto.java
  src/main/java/com/dku/council/domain/report/model/entity/Report.java
  src/main/java/com/dku/council/domain/report/model/entity/ReportCategory.java
  src/main/java/com/dku/council/domain/report/repository/ReportRepository.java
  src/main/java/com/dku/council/domain/report/service/ReportService.java
  src/main/java/com/dku/council/global/auth/role/UserAuthNames.java
  src/main/java/com/dku/council/infra/nhn/service/SMSService.java
  src/test/java/com/dku/council/domain/report/repository/ReportRepositoryTest.java
Labels: deploy

#391 pinpoint cloud로 이전
  Dockerfile
Labels: chore

#392 개발 서버에 배포
  Dockerfile
Labels: deploy

#393 Actuator/Prometheus 설정
  build.gradle
Labels: chore

#394 개발 서버 배포
  build.gradle
Labels: deploy

#395 운영 서버 배포
  Dockerfile
  build.gradle
Labels: deploy
