Repository EveryUniv/student-council-homepage-backend, pull requests merged in 2023-04, with the labels that each got.

#214 버스 오류 수정
  src/main/java/com/dku/council/domain/bus/model/CachedBusArrivals.java
  src/main/java/com/dku/council/domain/bus/repository/impl/BusArrivalRedisRepository.java
  src/main/java/com/dku/council/global/base/AbstractKeyValueCacheRepository.java
  src/main/java/com/dku/council/infra/bus/provider/GGBusProvider.java
  src/main/java/com/dku/council/infra/bus/provider/TownBusProvider.java
  src/main/resources/bustable/holiday/bearstatue/24.table
  src/main/resources/bustable/saturday/bearstatue/24.table
  src/main/resources/bustable/weekday/bearstatue/24.table
  src/test/java/com/dku/council/domain/bus/repository/impl/BusArrivalMemoryRepositoryTest.java
  src/test/java/com/dku/council/infra/bus/provider/TownBusProviderTest.java
  src/test/resources/mockdata/bus/kakao.json
Labels: bug

#215 동의인원수 오류 수정
  src/main/java/com/dku/council/domain/post/controller/PetitionController.java
  src/main/java/com/dku/council/domain/post/model/dto/response/ResponsePetitionDto.java
  src/main/java/com/dku/council/domain/post/service/PetitionService.java
  src/main/java/com/dku/council/domain/statistic/repository/PetitionStatisticRepository.java
  src/main/java/com/dku/council/domain/statistic/service/PetitionStatisticService.java
  src/test/java/com/dku/council/domain/post/controller/PetitionControllerTest.java
  src/test/java/com/dku/council/domain/post/service/GenericPostServiceTest.java
  src/test/java/com/dku/council/domain/post/service/PetitionServiceTest.java
  src/test/java/com/dku/council/domain/statistic/service/PetitionStatisticServiceTest.java
  src/test/java/com/dku/council/mock/PetitionStatisticMock.java
Labels: bug

#216 학생 정보 새로고침 API
  src/main/java/com/dku/council/domain/user/controller/DKUController.java
  src/main/java/com/dku/council/domain/user/controller/EmailController.java
  src/main/java/com/dku/council/domain/user/model/DkuUserInfo.java
  src/main/java/com/dku/council/domain/user/model/dto/request/RequestDkuStudentDto.java
  src/main/java/com/dku/council/domain/user/model/dto/response/ResponseScrappedStudentInfoDto.java
  src/main/java/com/dku/council/domain/user/model/entity/User.java
  src/main/java/com/dku/council/domain/user/service/DKUAuthService.java
  src/main/java/com/dku/council/domain/user/service/DkuEmailService.java
  src/main/java/com/dku/council/domain/user/service/SignupService.java
  src/test/java/com/dku/council/domain/user/service/DKUAuthServiceTest.java
  src/test/java/com/dku/council/domain/user/service/SignupServiceTest.java
Labels: feat

#217 자유게시판 DTO 수정
  src/main/java/com/dku/council/domain/post/controller/GeneralForumController.java
  src/main/java/com/dku/council/domain/post/model/dto/response/ResponseGeneralForumDto.java
  src/main/java/com/dku/council/domain/post/model/entity/posttype/GeneralForum.java
Labels: update

#218 좋아요 버그 수정
  src/main/java/com/dku/council/domain/like/model/entity/LikeElement.java
  src/main/java/com/dku/council/domain/like/repository/LikeMemoryRepository.java
  src/main/java/com/dku/council/domain/like/repository/impl/LikeRedisRepository.java
  src/main/java/com/dku/council/domain/like/service/impl/CachedLikeServiceImpl.java
  src/main/java/com/dku/council/global/config/redis/RedisKeys.java
  src/test/java/com/dku/council/domain/like/repository/impl/LikeRedisRepositoryTest.java
  src/test/java/com/dku/council/domain/like/service/CachedLikeServiceImplTest.java
Labels: bug

#221 테스트 수정
  src/main/java/com/dku/council/domain/user/service/SignupService.java
  src/test/java/com/dku/council/infra/bus/provider/TownBusProviderTest.java
  src/test/resources/mockdata/bus/kakao.json
Labels: test

#222 개발 서버로 배포
  src/main/java/com/dku/council/domain/bus/model/CachedBusArrivals.java
  src/main/java/com/dku/council/domain/bus/repository/impl/BusArrivalRedisRepository.java
  src/main/java/com/dku/council/domain/like/model/entity/LikeElement.java
  src/main/java/com/dku/council/domain/like/repository/LikeMemoryRepository.java
  src/main/java/com/dku/council/domain/like/repository/impl/LikeRedisRepository.java
  src/main/java/com/dku/council/domain/like/service/impl/CachedLikeServiceImpl.java
  src/main/java/com/dku/council/domain/post/controller/GeneralForumController.java
  src/main/java/com/dku/council/domain/post/controller/PetitionController.java
  src/main/java/com/dku/council/domain/post/model/dto/response/ResponseGeneralForumDto.java
  src/main/java/com/dku/council/domain/post/model/dto/response/ResponsePetitionDto.java
  src/main/java/com/dku/council/domain/post/model/entity/posttype/GeneralForum.java
  src/main/java/com/dku/council/domain/post/service/GenericPostService.java
  src/main/java/com/dku/council/domain/post/service/PetitionService.java
  src/main/java/com/dku/council/domain/statistic/repository/PetitionStatisticRepository.java
  src/main/java/com/dku/council/domain/statistic/service/PetitionStatisticService.java
  src/main/java/com/dku/council/domain/user/controller/DKUController.java
  src/main/java/com/dku/council/domain/user/controller/EmailController.java
  src/main/java/com/dku/council/domain/user/model/DkuUserInfo.java
  src/main/java/com/dku/council/domain/user/model/dto/request/RequestDkuStudentDto.java
  src/main/java/com/dku/council/domain/user/model/dto/response/ResponseScrappedStudentInfoDto.java
  src/main/java/com/dku/council/domain/user/model/entity/User.java
  src/main/java/com/dku/council/domain/user/service/DKUAuthService.java
  src/main/java/com/dku/council/domain/user/service/DkuEmailService.java
  src/main/java/com/dku/council/domain/user/service/SignupService.java
  src/main/java/com/dku/council/global/base/AbstractKeyValueCacheRepository.java
  src/main/java/com/dku/council/global/config/redis/RedisKeys.java
  src/main/java/com/dku/council/infra/bus/provider/GGBusProvider.java
  src/main/java/com/dku/council/infra/bus/provider/TownBusProvider.java
  src/main/resources/bustable/holiday/bearstatue/24.table
  src/main/resources/bustable/saturday/bearstatue/24.table
  src/main/resources/bustable/weekday/bearstatue/24.table
  src/test/java/com/dku/council/domain/bus/repository/impl/BusArrivalMemoryRepositoryTest.java
  src/test/java/com/dku/council/domain/like/repository/impl/LikeRedisRepositoryTest.java
  src/test/java/com/dku/council/domain/like/service/CachedLikeServiceImplTest.java
  src/test/java/com/dku/council/domain/post/controller/PetitionControllerTest.java
  src/test/java/com/dku/council/domain/post/service/GenericPostServiceTest.java
  src/test/java/com/dku/council/domain/post/service/PetitionServiceTest.java
  src/test/java/com/dku/council/domain/statistic/service/PetitionStatisticServiceTest.java
  src/test/java/com/dku/council/domain/user/service/DKUAuthServiceTest.java
  src/test/java/com/dku/council/domain/user/service/SignupServiceTest.java
  src/test/java/com/dku/council/infra/bus/provider/TownBusProviderTest.java
  src/test/java/com/dku/council/mock/PetitionStatisticMock.java
  src/test/resources/mockdata/bus/kakao.json
Labels: deploy

#223 자유게시판 댓글 익명 -> 학과 + 닉네임
  src/main/java/com/dku/council/domain/comment/service/CommentService.java
  src/main/java/com/dku/council/domain/post/controller/GeneralForumController.java
  src/test/java/com/dku/council/domain/comment/service/CommentServiceTest.java
  src/test/java/com/dku/council/domain/post/service/GenericPostServiceTest.java
  src/test/java/com/dku/council/mock/CommentMock.java
  src/test/java/com/dku/council/mock/GeneralForumMock.java
Labels: fix

#226 댓글 DTO 수정
  src/main/java/com/dku/council/domain/comment/service/CommentService.java
  src/main/java/com/dku/council/domain/post/controller/GeneralForumController.java
  src/main/java/com/dku/council/domain/post/controller/PetitionController.java
  src/main/java/com/dku/council/domain/post/model/dto/response/GeneralForumCommentDto.java
  src/main/java/com/dku/council/domain/post/model/dto/response/ResponsePetitionDto.java
  src/main/java/com/dku/council/domain/post/service/PetitionService.java
  src/main/java/com/dku/council/domain/statistic/model/dto/PetitionStatisticDto.java
  src/main/java/com/dku/council/domain/statistic/repository/PetitionStatisticRepository.java
  src/main/java/com/dku/council/domain/statistic/service/PetitionStatisticService.java
  src/test/java/com/dku/council/domain/comment/service/CommentServiceTest.java
  src/test/java/com/dku/council/domain/post/controller/PetitionControllerTest.java
  src/test/java/com/dku/council/domain/post/service/PetitionServiceTest.java
  src/test/java/com/dku/council/domain/statistic/service/PetitionStatisticServiceTest.java
  src/test/java/com/dku/council/mock/PetitionStatisticMock.java
Labels: update

#228 영어 메시지 추가
  src/main/resources/errors_en_US.properties
  src/main/resources/messages_en_US.properties
Labels: update

#229 개발 서버에 배포
  src/main/java/com/dku/council/domain/comment/model/dto/CommentDto.java
  src/main/java/com/dku/council/domain/comment/service/CommentService.java
  src/main/java/com/dku/council/domain/post/controller/GeneralForumController.java
  src/main/java/com/dku/council/domain/post/controller/PetitionController.java
  src/main/java/com/dku/council/domain/post/model/dto/list/SummarizedGenericPostDto.java
  src/main/java/com/dku/council/domain/post/model/dto/response/GeneralForumCommentDto.java
  src/main/java/com/dku/council/domain/post/model/dto/response/ResponsePetitionDto.java
  src/main/java/com/dku/council/domain/post/service/PetitionService.java
  src/main/java/com/dku/council/domain/statistic/model/dto/PetitionStatisticDto.java
  src/main/java/com/dku/council/domain/statistic/repository/PetitionStatisticRepository.java
  src/main/java/com/dku/council/domain/statistic/service/PetitionStatisticService.java
  src/main/java/com/dku/council/domain/user/model/dto/response/ResponseLoginDto.java
  src/main/java/com/dku/council/domain/user/model/dto/response/ResponseUserInfoDto.java
  src/main/java/com/dku/council/domain/user/service/UserService.java
  src/main/resources/errors_en_US.properties
  src/main/resources/messages_en_US.properties
  src/test/java/com/dku/council/domain/comment/service/CommentServiceTest.java
  src/test/java/com/dku/council/domain/post/controller/PetitionControllerTest.java
  src/test/java/com/dku/council/domain/post/service/GenericPostServiceTest.java
  src/test/java/com/dku/council/domain/post/service/PetitionServiceTest.java
  src/test/java/com/dku/council/domain/statistic/service/PetitionStatisticServiceTest.java
  src/test/java/com/dku/council/domain/user/service/UserServiceTest.java
  src/test/java/com/dku/council/mock/CommentMock.java
  src/test/java/com/dku/council/mock/GeneralForumMock.java
  src/test/java/com/dku/council/mock/PetitionStatisticMock.java
Labels: deploy

#230 운영 서버에 배포
  src/main/java/com/dku/council/domain/bus/model/CachedBusArrivals.java
  src/main/java/com/dku/council/domain/bus/repository/impl/BusArrivalRedisRepository.java
  src/main/java/com/dku/council/domain/comment/model/dto/CommentDto.java
  src/main/java/com/dku/council/domain/comment/service/CommentService.java
  src/main/java/com/dku/council/domain/like/model/entity/LikeElement.java
  src/main/java/com/dku/council/domain/like/repository/LikeMemoryRepository.java
  src/main/java/com/dku/council/domain/like/repository/impl/LikeRedisRepository.java
  src/main/java/com/dku/council/domain/like/service/impl/CachedLikeServiceImpl.java
  src/main/java/com/dku/council/domain/post/controller/GeneralForumController.java
  src/main/java/com/dku/council/domain/post/controller/PetitionController.java
  src/main/java/com/dku/council/domain/post/model/dto/list/SummarizedGenericPostDto.java
  src/main/java/com/dku/council/domain/post/model/dto/response/GeneralForumCommentDto.java
  src/main/java/com/dku/council/domain/post/model/dto/response/ResponseGeneralForumDto.java
  src/main/java/com/dku/council/domain/post/model/dto/response/ResponsePetitionDto.java
  src/main/java/com/dku/council/domain/post/model/entity/posttype/GeneralForum.java
  src/main/java/com/dku/council/domain/post/service/GenericPostService.java
  src/main/java/com/dku/council/domain/post/service/PetitionService.java
  src/main/java/com/dku/council/domain/statistic/model/dto/PetitionStatisticDto.java
  src/main/java/com/dku/council/domain/statistic/repository/PetitionStatisticRepository.java
  src/main/java/com/dku/council/domain/statistic/service/PetitionStatisticService.java
  src/main/java/com/dku/council/domain/user/controller/DKUController.java
  src/main/java/com/dku/council/domain/user/controller/EmailController.java
  src/main/java/com/dku/council/domain/user/model/DkuUserInfo.java
  src/main/java/com/dku/council/domain/user/model/dto/request/RequestDkuStudentDto.java
  src/main/java/com/dku/council/domain/user/model/dto/response/ResponseLoginDto.java
  src/main/java/com/dku/council/domain/user/model/dto/response/ResponseScrappedStudentInfoDto.java
  src/main/java/com/dku/council/domain/user/model/dto/response/ResponseUserInfoDto.java
  src/main/java/com/dku/council/domain/user/model/entity/User.java
  src/main/java/com/dku/council/domain/user/service/DKUAuthService.java
  src/main/java/com/dku/council/domain/user/service/DkuEmailService.java
  src/main/java/com/dku/council/domain/user/service/SignupService.java
  src/main/java/com/dku/council/domain/user/service/UserService.java
  src/main/java/com/dku/council/global/base/AbstractKeyValueCacheRepository.java
  src/main/java/com/dku/council/global/config/redis/RedisKeys.java
  src/main/java/com/dku/council/infra/bus/provider/GGBusProvider.java
  src/main/java/com/dku/council/infra/bus/provider/TownBusProvider.java
  src/main/resources/bustable/holiday/bearstatue/24.table
  src/main/resources/bustable/saturday/bearstatue/24.table
  src/main/resources/bustable/weekday/bearstatue/24.table
  src/main/resources/errors_en_US.properties
  src/main/resources/messages_en_US.properties
  src/test/java/com/dku/council/domain/bus/repository/impl/BusArrivalMemoryRepositoryTest.java
  src/test/java/com/dku/council/domain/comment/service/CommentServiceTest.java
  src/test/java/com/dku/council/domain/like/repository/impl/LikeRedisRepositoryTest.java
  src/test/java/com/dku/council/domain/like/service/CachedLikeServiceImplTest.java
  src/test/java/com/dku/council/domain/post/controller/PetitionControllerTest.java
  src/test/java/com/dku/council/domain/post/service/GenericPostServiceTest.java
  src/test/java/com/dku/council/domain/post/service/PetitionServiceTest.java
  src/test/java/com/dku/council/domain/statistic/service/PetitionStatisticServiceTest.java
  src/test/java/com/dku/council/domain/user/service/DKUAuthServiceTest.java
  src/test/java/com/dku/council/domain/user/service/SignupServiceTest.java
  src/test/java/com/dku/council/domain/user/service/UserServiceTest.java
  src/test/java/com/dku/council/infra/bus/provider/TownBusProviderTest.java
  src/test/java/com/dku/council/mock/CommentMock.java
  src/test/java/com/dku/council/mock/GeneralForumMock.java
  src/test/java/com/dku/council/mock/PetitionStatisticMock.java
  src/test/resources/mockdata/bus/kakao.json
Labels: deploy

#231 테스트 수정
  src/test/java/com/dku/council/domain/post/controller/PetitionControllerTest.java
Labels: bug, test

#233 배포 - 운영
  src/test/java/com/dku/council/domain/post/controller/PetitionControllerTest.java
Labels: deploy

#244 내 정보에 관리자 확인할 수 있는 필드
  src/main/java/com/dku/council/domain/user/model/dto/response/ResponseUserInfoDto.java
  src/main/java/com/dku/council/domain/user/service/UserService.java
  src/test/java/com/dku/council/domain/user/service/UserServiceTest.java
Labels: update

#252 Comment 닉네임화
  src/main/java/com/dku/council/domain/post/controller/GeneralForumController.java
  src/main/java/com/dku/council/domain/post/controller/PetitionController.java
Labels: bug, update

#254 학생회비 크롤링 제외 및 dto 업데이트
  Dockerfile
  src/main/java/com/dku/council/debug/TestController.java
  src/main/java/com/dku/council/domain/timetable/model/dto/response/LectureTemplateDto.java
  src/main/java/com/dku/council/domain/timetable/model/entity/LectureTemplate.java
  src/main/java/com/dku/council/domain/timetable/service/LectureRetrieveService.java
  src/main/java/com/dku/council/domain/user/model/DkuUserInfo.java
  src/main/java/com/dku/council/domain/user/model/dto/response/ResponseLoginDto.java
  src/main/java/com/dku/council/domain/user/model/entity/User.java
  src/main/java/com/dku/council/domain/user/service/DKUAuthService.java
  src/main/java/com/dku/council/domain/user/service/DkuEmailService.java
  src/main/java/com/dku/council/domain/user/service/SignupService.java
  src/main/java/com/dku/council/domain/user/service/UserService.java
  src/test/java/com/dku/council/domain/timetable/controller/TimeTableControllerTest.java
  src/test/java/com/dku/council/domain/timetable/service/LectureRetrieveServiceTest.java
  src/test/java/com/dku/council/domain/user/service/DKUAuthServiceTest.java
  src/test/java/com/dku/council/domain/user/service/SignupServiceTest.java
  src/test/java/com/dku/council/domain/user/service/UserServiceTest.java
  src/test/java/com/dku/council/mock/UserMock.java
Labels: update

#258 Petition Dto 수정
  src/main/java/com/dku/council/domain/post/model/dto/list/SummarizedGenericPostDto.java
  src/main/java/com/dku/council/domain/post/model/dto/response/ResponsePetitionDto.java
  src/main/java/com/dku/council/domain/post/service/PetitionService.java
  src/main/java/com/dku/council/domain/statistic/service/PetitionStatisticService.java
  src/test/java/com/dku/council/domain/post/service/PetitionServiceTest.java
Labels: update

#257 페이징 버그 수정
  src/main/java/com/dku/council/domain/post/model/dto/list/SummarizedGenericPostDto.java
  src/main/java/com/dku/council/domain/post/model/dto/response/ResponsePage.java
Labels: bug

#260 중간 리팩토링
  src/main/java/com/dku/council/domain/post/service/PetitionService.java
  src/main/java/com/dku/council/domain/statistic/model/dto/AgreeCount.java
  src/main/java/com/dku/council/domain/statistic/model/dto/PetitionStatisticDto.java
  src/main/java/com/dku/council/domain/statistic/model/entity/PetitionStatistic.java
  src/main/java/com/dku/council/domain/statistic/repository/PetitionStatisticRepository.java
  src/main/java/com/dku/council/domain/statistic/service/PetitionStatisticService.java
  src/test/java/com/dku/council/domain/post/controller/PetitionControllerTest.java
  src/test/java/com/dku/council/domain/post/service/PetitionServiceTest.java
  src/test/java/com/dku/council/domain/statistic/repository/PetitionStatisticRepositoryTest.java
  src/test/java/com/dku/council/domain/statistic/service/PetitionStatisticServiceTest.java
  src/test/java/com/dku/council/mock/MajorMock.java
  src/test/java/com/dku/council/mock/PetitionStatisticMock.java
Labels: refactor

#270 개발 서버에 배포
  src/main/java/com/dku/council/debug/TestDto.java
  src/main/java/com/dku/council/debug/controller/AdminController.java
  src/main/java/com/dku/council/debug/controller/TestController.java
  src/main/java/com/dku/council/debug/model/ErrorLog.java
  src/main/java/com/dku/council/debug/service/ErrorLogService.java
  src/main/java/com/dku/council/global/error/ControllerAdvisor.java
Labels: deploy

#271 테스트 수정
  src/test/java/com/dku/council/domain/timetable/controller/TimeTableControllerTest.java
Labels: test

#272 개발 서버로 배포
  src/test/java/com/dku/council/domain/timetable/controller/TimeTableControllerTest.java
Labels: deploy

#264 JPA 최적화
  src/main/java/com/dku/council/domain/mainpage/model/dto/request/RequestCarouselImageDto.java
  src/main/java/com/dku/council/domain/mainpage/model/entity/Schedule.java
  src/main/java/com/dku/council/domain/post/controller/PetitionController.java
  src/main/java/com/dku/council/domain/post/model/dto/list/SummarizedGenericPostDto.java
  src/main/java/com/dku/council/domain/post/repository/post/GenericPostRepository.java
  src/main/java/com/dku/council/domain/rental/model/dto/RentalDto.java
  src/main/java/com/dku/council/domain/rental/repository/RentalRepository.java
  src/main/java/com/dku/council/domain/report/model/dto/response/ResponseReportCategoryCountDto.java
  src/main/java/com/dku/council/domain/report/model/dto/response/ResponseSingleReportedPostDto.java
  src/main/java/com/dku/council/domain/report/model/dto/response/SummarizedReportedPostDto.java
  src/main/java/com/dku/council/domain/report/model/entity/Report.java
  src/main/java/com/dku/council/domain/report/service/ReportService.java
  src/main/java/com/dku/council/domain/statistic/repository/PetitionStatisticRepository.java
  src/main/java/com/dku/council/domain/statistic/service/PetitionStatisticService.java
  src/main/java/com/dku/council/domain/timetable/model/entity/LectureTemplate.java
  src/main/java/com/dku/council/domain/user/model/UserStatus.java
  src/main/java/com/dku/council/domain/user/model/entity/User.java
  src/test/java/com/dku/council/domain/statistic/service/PetitionStatisticServiceTest.java
Labels: refactor

#273 대여 물품 API 수정
  src/main/java/com/dku/council/domain/rental/controller/RentalController.java
  src/main/java/com/dku/council/domain/rental/model/RentalUserClass.java
  src/main/java/com/dku/council/domain/rental/model/dto/SummarizedRentalDto.java
  src/main/java/com/dku/council/domain/rental/model/entity/Rental.java
  src/main/java/com/dku/council/domain/rental/repository/RentalRepository.java
  src/main/java/com/dku/council/domain/rental/service/RentalService.java
  src/test/java/com/dku/council/domain/rental/controller/RentalControllerTest.java
  src/test/java/com/dku/council/domain/rental/service/RentalServiceTest.java
Labels: update

#277 Main 페이지 blind 청원 보이는 버그
  src/main/java/com/dku/council/domain/mainpage/model/dto/PetitionSummary.java
  src/main/java/com/dku/council/domain/mainpage/service/MainPageService.java
  src/main/java/com/dku/council/domain/post/repository/post/PetitionRepository.java
Labels: bug

#280 배포 전 버그 수정
  src/main/java/com/dku/council/domain/timetable/exception/TimeConflictException.java
  src/main/java/com/dku/council/domain/timetable/exception/TooSmallTimeException.java
  src/main/java/com/dku/council/domain/timetable/model/dto/TimePromise.java
  src/main/java/com/dku/council/domain/timetable/service/TimeTableService.java
  src/main/java/com/dku/council/global/error/exception/LocalizedMessageException.java
  src/main/resources/errors.properties
  src/main/resources/errors_en_US.properties
  src/test/java/com/dku/council/domain/timetable/controller/TimeTableControllerTest.java
  src/test/java/com/dku/council/domain/timetable/service/TimeTableServiceTest.java
  src/test/java/com/dku/council/mock/LectureMock.java
  src/test/java/com/dku/council/mock/LectureTemplateMock.java
Labels: bug

#281 개발 서버에 배포
  src/main/java/com/dku/council/domain/mainpage/model/dto/PetitionSummary.java
  src/main/java/com/dku/council/domain/mainpage/service/MainPageService.java
  src/main/java/com/dku/council/domain/post/repository/post/PetitionRepository.java
  src/main/java/com/dku/council/domain/timetable/exception/TimeConflictException.java
  src/main/java/com/dku/council/domain/timetable/exception/TooSmallTimeException.java
  src/main/java/com/dku/council/domain/timetable/model/dto/TimePromise.java
  src/main/java/com/dku/council/domain/timetable/service/TimeTableService.java
  src/main/java/com/dku/council/global/error/exception/LocalizedMessageException.java
  src/main/resources/errors.properties
  src/main/resources/errors_en_US.properties
  src/test/java/com/dku/council/domain/timetable/controller/TimeTableControllerTest.java
  src/test/java/com/dku/council/domain/timetable/service/TimeTableServiceTest.java
  src/test/java/com/dku/council/mock/LectureMock.java
  src/test/java/com/dku/council/mock/LectureTemplateMock.java
Labels: deploy

#283 Enable pinpoint
  Dockerfile
Labels: chore

#284 개발 서버에 배포
  Dockerfile
Labels: deploy

#288 문서 수정
  README.md
  docs/README.md
  docs/images/board.png
  docs/images/domain_model.png
  docs/images/erd.png
  docs/images/server_arch.png
  docs/rules.md
  src/main/java/com/dku/council/domain/mainpage/model/dto/request/RequestCarouselImageDto.java
Labels: docs

#289 main에 문서 반영
  README.md
  docs/README.md
  docs/images/board.png
  docs/images/domain_model.png
  docs/images/erd.png
  docs/images/server_arch.png
  docs/rules.md
  src/main/java/com/dku/council/domain/mainpage/model/dto/request/RequestCarouselImageDto.java
Labels: docs, deploy

#291 좋아요 수 동시성 문제 해결
  src/main/java/com/dku/council/domain/like/repository/LikeMemoryRepository.java
  src/main/java/com/dku/council/domain/like/repository/impl/LikeRedisRepository.java
  src/main/java/com/dku/council/domain/like/service/impl/CachedLikeServiceImpl.java
  src/test/java/com/dku/council/domain/like/repository/impl/LikeRedisRepositoryTest.java
  src/test/java/com/dku/council/domain/like/service/CachedLikeServiceConcurrencyTest.java
  src/test/java/com/dku/council/domain/like/service/CachedLikeServiceImplTest.java
Labels: bug

#300 메시지 수정
  src/main/resources/errors.properties
  src/main/resources/errors_en_US.properties
  src/test/java/com/dku/council/domain/mainpage/service/MainPageServiceTest.java
  src/test/resources/errors.properties
Labels: update

#302 개발 서버에 배포
  src/main/resources/errors.properties
  src/main/resources/errors_en_US.properties
  src/test/java/com/dku/council/domain/mainpage/service/MainPageServiceTest.java
  src/test/resources/errors.properties
Labels: deploy

#296 총학소식 권한 수정
  src/main/java/com/dku/council/domain/post/controller/NewsController.java
  src/main/java/com/dku/council/domain/post/repository/post/GenericPostRepository.java
  src/main/java/com/dku/council/domain/post/service/post/GenericPostService.java
  src/main/java/com/dku/council/domain/post/service/post/NewsService.java
  src/main/java/com/dku/council/global/auth/role/GuestAuth.java
Labels: bug

#303 Fix : managePage 접근 권한
  src/main/java/com/dku/council/global/auth/jwt/JwtProvider.java
Labels: bug

#309 관리자 페이지 운영자만 허용
  src/main/java/com/dku/council/global/config/SecurityConfig.java
Labels: bug

#314 시간표 API 간소화
  src/main/java/com/dku/council/domain/timetable/model/TimeScheduleType.java
  src/main/java/com/dku/council/domain/timetable/model/dto/request/RequestScheduleDto.java
  src/main/java/com/dku/council/domain/timetable/model/dto/response/LectureTemplateDto.java
  src/main/java/com/dku/council/domain/timetable/model/dto/response/TimeScheduleDto.java
  src/main/java/com/dku/council/domain/timetable/model/entity/TimeSchedule.java
  src/main/java/com/dku/council/domain/timetable/service/TimeTableService.java
  src/test/java/com/dku/council/domain/timetable/controller/TimeTableControllerTest.java
  src/test/java/com/dku/council/domain/timetable/service/TimeTableServiceTest.java
Labels: update

#317 개발 서버에 배포
  src/main/java/com/dku/council/domain/timetable/service/TimeTableService.java
  src/test/java/com/dku/council/domain/timetable/service/TimeTableServiceTest.java
  src/test/java/com/dku/council/mock/LectureMock.java
Labels: deploy

#323 티켓팅 동시성 문제
  build.gradle
  src/main/java/com/dku/council/domain/batch/LikeDumpScheduler.java
  src/main/java/com/dku/council/domain/like/repository/LikeMemoryRepository.java
  src/main/java/com/dku/council/domain/like/repository/impl/LikeRedisRepository.java
  src/main/java/com/dku/council/domain/like/service/impl/CachedLikeServiceImpl.java
  src/main/java/com/dku/council/domain/ticket/repository/impl/TicketRedisRepository.java
  src/main/java/com/dku/council/domain/ticket/service/TicketService.java
  src/main/java/com/dku/council/global/config/redis/RedisConfig.java
  src/main/java/com/dku/council/global/config/redis/RedisKeys.java
  src/main/java/com/dku/council/infra/naver/service/CaptchaService.java
  src/test/java/com/dku/council/domain/like/repository/impl/LikeRedisRepositoryTest.java
  src/test/java/com/dku/council/domain/like/service/CachedLikeServiceImplTest.java
  src/test/java/com/dku/council/domain/ticket/repository/impl/TicketRedisRepositoryTest.java
  src/test/java/com/dku/council/domain/ticket/service/TicketConcurrencyTest.java
  src/test/java/com/dku/council/domain/ticket/service/TicketServiceTest.java
  src/test/java/com/dku/council/infra/naver/service/CaptchaServiceTest.java
  src/test/java/com/dku/council/util/base/AbstractContainerRedisTest.java
Labels: bug

#324 개발 서버에 배포
  build.gradle
  src/main/java/com/dku/council/domain/batch/LikeDumpScheduler.java
  src/main/java/com/dku/council/domain/like/repository/LikeMemoryRepository.java
  src/main/java/com/dku/council/domain/like/repository/impl/LikeRedisRepository.java
  src/main/java/com/dku/council/domain/like/service/impl/CachedLikeServiceImpl.java
  src/main/java/com/dku/council/domain/ticket/repository/impl/TicketRedisRepository.java
  src/main/java/com/dku/council/domain/ticket/service/TicketService.java
  src/main/java/com/dku/council/global/config/redis/RedisConfig.java
  src/main/java/com/dku/council/global/config/redis/RedisKeys.java
  src/main/java/com/dku/council/infra/naver/service/CaptchaService.java
  src/test/java/com/dku/council/domain/like/repository/impl/LikeRedisRepositoryTest.java
  src/test/java/com/dku/council/domain/like/service/CachedLikeServiceImplTest.java
  src/test/java/com/dku/council/domain/ticket/repository/impl/TicketRedisRepositoryTest.java
  src/test/java/com/dku/council/domain/ticket/service/TicketConcurrencyTest.java
  src/test/java/com/dku/council/domain/ticket/service/TicketServiceTest.java
  src/test/java/com/dku/council/infra/naver/service/CaptchaServiceTest.java
  src/test/java/com/dku/council/util/base/AbstractContainerRedisTest.java
Labels: deploy

#325 Auto-sms-send 설정 추가
  src/main/java/com/dku/council/domain/ticket/model/entity/Ticket.java
  src/main/java/com/dku/council/domain/ticket/service/TicketVerifyService.java
  src/test/java/com/dku/council/domain/ticket/service/TicketVerifyServiceTest.java
Labels: feat

#327 운영 서버에 배포
  build.gradle
  src/main/java/com/dku/council/domain/batch/LikeDumpScheduler.java
  src/main/java/com/dku/council/domain/like/repository/LikeMemoryRepository.java
  src/main/java/com/dku/council/domain/like/repository/impl/LikeRedisRepository.java
  src/main/java/com/dku/council/domain/like/service/impl/CachedLikeServiceImpl.java
  src/main/java/com/dku/council/domain/ticket/model/entity/Ticket.java
  src/main/java/com/dku/council/domain/ticket/repository/impl/TicketRedisRepository.java
  src/main/java/com/dku/council/domain/ticket/service/TicketService.java
  src/main/java/com/dku/council/domain/ticket/service/TicketVerifyService.java
  src/main/java/com/dku/council/global/config/redis/RedisConfig.java
  src/main/java/com/dku/council/global/config/redis/RedisKeys.java
  src/main/java/com/dku/council/infra/naver/service/CaptchaService.java
  src/test/java/com/dku/council/domain/like/repository/impl/LikeRedisRepositoryTest.java
  src/test/java/com/dku/council/domain/like/service/CachedLikeServiceImplTest.java
  src/test/java/com/dku/council/domain/ticket/repository/impl/TicketRedisRepositoryTest.java
  src/test/java/com/dku/council/domain/ticket/service/TicketConcurrencyTest.java
  src/test/java/com/dku/council/domain/ticket/service/TicketServiceTest.java
  src/test/java/com/dku/council/domain/ticket/service/TicketVerifyServiceTest.java
  src/test/java/com/dku/council/infra/naver/service/CaptchaServiceTest.java
  src/test/java/com/dku/council/util/base/AbstractContainerRedisTest.java
Labels: deploy

#329 티케팅 운영 서버 핫픽스
  src/main/java/com/dku/council/domain/batch/TicketScheduler.java
  src/main/java/com/dku/council/domain/ticket/repository/impl/TicketRedisRepository.java
Labels: deploy
