Repository EveryUniv/student-council-homepage-backend, pull requests merged in 2023-03, with the labels that each got.

#53 단대 크롤링 버그
  src/main/java/com/dku/council/domain/user/model/dto/request/RequestSendSMSCodeDto.java
  src/main/java/com/dku/council/global/base/BaseEntity.java
  src/main/java/com/dku/council/global/util/WebUtil.java
  src/main/java/com/dku/council/infra/dku/service/DkuAuthenticationService.java
  src/test/java/com/dku/council/global/util/WebUtilTest.java
  src/test/java/com/dku/council/infra/dku/service/DkuAuthenticationServiceTest.java
  src/test/resources/mockdata/dku/failed-login-response.html
  src/test/resources/mockdata/dku/login-response.html
Labels: bug

#62 태그 시스템으로 전환
  docs/images/domain_model.png
  docs/images/erd.png
  src/main/java/com/dku/council/domain/category/controller/CategoryController.java
  src/main/java/com/dku/council/domain/category/exception/CategoryIntegrityException.java
  src/main/java/com/dku/council/domain/category/exception/CategoryNotFoundException.java
  src/main/java/com/dku/council/domain/category/model/dto/CategoryDto.java
  src/main/java/com/dku/council/domain/category/repository/CategoryRepository.java
  src/main/java/com/dku/council/domain/category/service/CategoryService.java
  src/main/java/com/dku/council/domain/comment/CommentRepository.java
  src/main/java/com/dku/council/domain/comment/model/entity/Comment.java
  src/main/java/com/dku/council/domain/comment/service/CommentService.java
  src/main/java/com/dku/council/domain/post/config/PostConfig.java
  src/main/java/com/dku/council/domain/post/controller/GeneralForumController.java
  src/main/java/com/dku/council/domain/post/controller/NewsController.java
  src/main/java/com/dku/council/domain/post/controller/PetitionController.java
  src/main/java/com/dku/council/domain/post/model/dto/page/SummarizedGeneralForumDto.java
  src/main/java/com/dku/council/domain/post/model/dto/request/RequestCreateConferenceDto.java
  src/main/java/com/dku/council/domain/post/model/dto/request/RequestCreateGeneralForumDto.java
  src/main/java/com/dku/council/domain/post/model/dto/request/RequestCreateGenericPostDto.java
  src/main/java/com/dku/council/domain/post/model/dto/request/RequestCreateNewsDto.java
  src/main/java/com/dku/council/domain/post/model/dto/request/RequestCreatePetitionDto.java
  src/main/java/com/dku/council/domain/post/model/dto/request/RequestCreateRuleDto.java
  src/main/java/com/dku/council/domain/post/model/dto/response/ResponseSingleGenericPostDto.java
  src/main/java/com/dku/council/domain/post/model/entity/Post.java
  src/main/java/com/dku/council/domain/post/model/entity/posttype/Conference.java
  src/main/java/com/dku/council/domain/post/model/entity/posttype/GeneralForum.java
  src/main/java/com/dku/council/domain/post/model/entity/posttype/News.java
  src/main/java/com/dku/council/domain/post/model/entity/posttype/Petition.java
  src/main/java/com/dku/council/domain/post/model/entity/posttype/Rule.java
  src/main/java/com/dku/council/domain/post/repository/spec/PostSpec.java
  src/main/java/com/dku/council/domain/post/service/GenericPostService.java
  src/main/java/com/dku/council/domain/tag/controller/TagController.java
  src/main/java/com/dku/council/domain/tag/exception/TagIntegrityException.java
  src/main/java/com/dku/council/domain/tag/exception/TagNotFoundException.java
  src/main/java/com/dku/council/domain/tag/model/dto/RequestCreateTagDto.java
  src/main/java/com/dku/council/domain/tag/model/dto/RequestRenameTagDto.java
  src/main/java/com/dku/council/domain/tag/model/dto/TagDto.java
  src/main/java/com/dku/council/domain/tag/model/entity/PostTag.java
  src/main/java/com/dku/council/domain/tag/model/entity/Tag.java
  src/main/java/com/dku/council/domain/tag/repository/PostTagRepository.java
  src/main/java/com/dku/council/domain/tag/repository/TagRepository.java
  src/main/java/com/dku/council/domain/tag/service/TagService.java
  src/main/resources/errors.properties
  src/test/java/com/dku/council/domain/category/service/CategoryServiceTest.java
  src/test/java/com/dku/council/domain/comment/service/CommentServiceTest.java
  src/test/java/com/dku/council/domain/post/controller/NewsControllerTest.java
  src/test/java/com/dku/council/domain/post/controller/PetitionControllerTest.java
  src/test/java/com/dku/council/domain/post/repository/spec/PostSpecTest.java
  src/test/java/com/dku/council/domain/post/service/GenericPostServiceTest.java
  src/test/java/com/dku/council/domain/tag/service/TagServiceTest.java
  src/test/java/com/dku/council/mock/CategoryMock.java
  src/test/java/com/dku/council/mock/CommentMock.java
  src/test/java/com/dku/council/mock/NewsMock.java
  src/test/java/com/dku/council/mock/TagMock.java
  src/test/java/com/dku/council/util/PropertiesBase64Encoder.java
  src/test/resources/errors.properties
Labels: feat

#64 목록에 본문 및 글자 제한 추가
  src/main/java/com/dku/council/domain/post/controller/ConferenceController.java
  src/main/java/com/dku/council/domain/post/controller/GeneralForumController.java
  src/main/java/com/dku/council/domain/post/controller/NewsController.java
  src/main/java/com/dku/council/domain/post/controller/PetitionController.java
  src/main/java/com/dku/council/domain/post/controller/RuleController.java
  src/main/java/com/dku/council/domain/post/model/dto/page/SummarizedConferenceDto.java
  src/main/java/com/dku/council/domain/post/model/dto/page/SummarizedGeneralForumDto.java
  src/main/java/com/dku/council/domain/post/model/dto/page/SummarizedGenericPostDto.java
  src/main/java/com/dku/council/domain/post/model/dto/page/SummarizedPetitionDto.java
  src/main/java/com/dku/council/domain/post/model/dto/page/SummarizedRuleDto.java
Labels: feat

#65 개발 서버에 배포
  src/main/java/com/dku/council/domain/post/controller/ConferenceController.java
  src/main/java/com/dku/council/domain/post/controller/GeneralForumController.java
  src/main/java/com/dku/council/domain/post/controller/NewsController.java
  src/main/java/com/dku/council/domain/post/controller/PetitionController.java
  src/main/java/com/dku/council/domain/post/controller/RuleController.java
  src/main/java/com/dku/council/domain/post/model/dto/page/SummarizedConferenceDto.java
  src/main/java/com/dku/council/domain/post/model/dto/page/SummarizedGeneralForumDto.java
  src/main/java/com/dku/council/domain/post/model/dto/page/SummarizedGenericPostDto.java
  src/main/java/com/dku/council/domain/post/model/dto/page/SummarizedPetitionDto.java
  src/main/java/com/dku/council/domain/post/model/dto/page/SummarizedRuleDto.java
Labels: deploy

#66 NewsTest에 OnlyDevTest 추가
  src/test/java/com/dku/council/domain/post/controller/NewsControllerTest.java
Labels: bug

#67 개발 서버에 배포
  src/test/java/com/dku/council/domain/post/controller/NewsControllerTest.java
Labels: deploy

#68 이름 변경 dto summarizedBody -> body
  src/main/java/com/dku/council/domain/post/model/dto/page/SummarizedGenericPostDto.java
Labels: bug

#74 @JsonCreator대신 자동 constructor property 삽입 설정
  docs/rules.md
  lombok.config
  src/main/java/com/dku/council/domain/comment/model/dto/RequestCreateCommentDto.java
  src/main/java/com/dku/council/domain/post/model/dto/request/RequestCreateReplyDto.java
  src/main/java/com/dku/council/domain/post/model/dto/response/ResponsePage.java
  src/main/java/com/dku/council/domain/user/model/dto/request/RequestLoginDto.java
  src/main/java/com/dku/council/domain/user/model/dto/request/RequestRefreshTokenDto.java
  src/main/java/com/dku/council/domain/user/model/dto/request/RequestSendSMSCodeDto.java
  src/main/java/com/dku/council/domain/user/model/dto/request/RequestSignupDto.java
  src/main/java/com/dku/council/domain/user/model/dto/request/RequestVerifySMSCodeDto.java
  src/main/java/com/dku/council/global/dto/ResponseIdDto.java
  src/main/java/com/dku/council/infra/nhn/model/dto/response/ResponseNHNCloudSMS.java
  src/main/java/com/dku/council/infra/nhn/model/dto/response/ResponseToken.java
Labels: refactor

#76 개발 서버에 배포
  docs/rules.md
  lombok.config
  src/main/java/com/dku/council/domain/bus/controller/BusController.java
  src/main/java/com/dku/council/domain/bus/model/Bus.java
  src/main/java/com/dku/council/domain/bus/model/BusStation.java
  src/main/java/com/dku/council/domain/bus/model/dto/BusArrivalDto.java
  src/main/java/com/dku/council/domain/bus/model/dto/ResponseBusArrivalDto.java
  src/main/java/com/dku/council/domain/bus/model/repository/CachedBusArrivals.java
  src/main/java/com/dku/council/domain/bus/repository/BusArrivalMemoryRepository.java
  src/main/java/com/dku/council/domain/bus/repository/impl/BusArrivalMemoryRepositoryImpl.java
  src/main/java/com/dku/council/domain/bus/service/BusService.java
  src/main/java/com/dku/council/domain/comment/model/dto/RequestCreateCommentDto.java
  src/main/java/com/dku/council/domain/post/model/dto/request/RequestCreateReplyDto.java
  src/main/java/com/dku/council/domain/post/model/dto/response/ResponsePage.java
  src/main/java/com/dku/council/domain/post/repository/ViewCountMemoryRepository.java
  src/main/java/com/dku/council/domain/user/model/dto/request/RequestLoginDto.java
  src/main/java/com/dku/council/domain/user/model/dto/request/RequestRefreshTokenDto.java
  src/main/java/com/dku/council/domain/user/model/dto/request/RequestSendSMSCodeDto.java
  src/main/java/com/dku/council/domain/user/model/dto/request/RequestSignupDto.java
  src/main/java/com/dku/council/domain/user/model/dto/request/RequestVerifySMSCodeDto.java
  src/main/java/com/dku/council/global/config/WebClientConfig.java
  src/main/java/com/dku/council/global/config/WebConfig.java
  src/main/java/com/dku/council/global/config/redis/RedisKeys.java
  src/main/java/com/dku/council/global/dto/ResponseIdDto.java
  src/main/java/com/dku/council/global/error/ControllerAdvisor.java
  src/main/java/com/dku/council/global/error/FieldErrorResult.java
  src/main/java/com/dku/council/global/error/exception/BindingFailedException.java
  src/main/java/com/dku/council/global/error/exception/MissingRequiredParamterException.java
  src/main/java/com/dku/council/global/error/exception/UnexpectedResponseException.java
  src/main/java/com/dku/council/infra/bus/exception/CannotGetBusArrivalException.java
  src/main/java/com/dku/council/infra/bus/exception/InvalidBusStationException.java
  src/main/java/com/dku/council/infra/bus/model/BusArrival.java
  src/main/java/com/dku/council/infra/bus/model/BusStatus.java
  src/main/java/com/dku/council/infra/bus/model/ResponseGGBusArrival.java
  src/main/java/com/dku/council/infra/bus/model/ResponseKakaoBusApi.java
  src/main/java/com/dku/council/infra/bus/model/mapper/BusResponseMapper.java
  src/main/java/com/dku/council/infra/bus/service/OpenApiBusService.java
  src/main/java/com/dku/council/infra/bus/service/api/BusArrivalInfoService.java
  src/main/java/com/dku/council/infra/bus/service/api/GGBusService.java
  src/main/java/com/dku/council/infra/bus/service/api/KakaoBusService.java
  src/main/java/com/dku/council/infra/nhn/model/dto/response/ResponseNHNCloudSMS.java
  src/main/java/com/dku/council/infra/nhn/model/dto/response/ResponseToken.java
  src/main/java/com/dku/council/infra/nhn/service/impl/SMSServiceImpl.java
  src/main/resources/errors.properties
  src/test/java/com/dku/council/domain/bus/repository/impl/BusArrivalMemoryRepositoryTest.java
  src/test/java/com/dku/council/domain/bus/service/BusServiceTest.java
  src/test/java/com/dku/council/domain/like/repository/impl/PostLikeRedisRepositoryTest.java
  src/test/java/com/dku/council/domain/post/repository/impl/ViewCountRedisRepositoryTest.java
  src/test/java/com/dku/council/domain/post/service/ViewCountServiceTest.java
  src/test/java/com/dku/council/infra/bus/service/OpenApiBusServiceTest.java
  src/test/java/com/dku/council/infra/bus/service/api/GGBusServiceTest.java
  src/test/java/com/dku/council/infra/bus/service/api/KakaoBusServiceTest.java
  src/test/java/com/dku/council/mock/BusArrivalMock.java
  src/test/java/com/dku/council/mock/ServerMock.java
  src/test/resources/errors.properties
  src/test/resources/mockdata/bus/getBusArrivalList-empty.xml
  src/test/resources/mockdata/bus/getBusArrivalList-failed.xml
  src/test/resources/mockdata/bus/getBusArrivalList.xml
  src/test/resources/mockdata/bus/kakao-failed.json
  src/test/resources/mockdata/bus/kakao.json
Labels: deploy

#78 개발 서버에 배포
  src/main/java/com/dku/council/infra/bus/service/api/KakaoBusService.java
Labels: deploy

#79 개발 서버에 배포
  src/test/java/com/dku/council/infra/bus/service/api/KakaoBusServiceTest.java
Labels: deploy

#70 이메일 인증
  src/main/java/com/dku/council/domain/like/PostLikeService.java
  src/main/java/com/dku/council/domain/user/controller/EmailController.java
  src/main/java/com/dku/council/domain/user/exception/WrongEmailCodeException.java
  src/main/java/com/dku/council/domain/user/model/dto/request/RequestSendEmailCode.java
  src/main/java/com/dku/council/domain/user/model/dto/request/RequestVerifyEmailCodeDto.java
  src/main/java/com/dku/council/domain/user/service/DkuEmailService.java
  src/main/java/com/dku/council/global/util/TextTemplateEngine.java
  src/main/java/com/dku/council/infra/nhn/model/dto/NhnMessage.java
  src/main/java/com/dku/council/infra/nhn/service/NHNEmailService.java
  src/main/java/com/dku/council/infra/nhn/service/impl/NHNEmailServiceImpl.java
  src/main/resources/auth_email_content.html
  src/main/resources/errors.properties
Labels: feat

#81 버스 API에 셔틀버스 추가
  src/main/java/com/dku/council/domain/bus/model/Bus.java
  src/main/java/com/dku/council/domain/bus/model/BusStation.java
  src/main/java/com/dku/council/infra/bus/model/BusStatus.java
  src/main/java/com/dku/council/infra/bus/service/OpenApiBusService.java
  src/main/java/com/dku/council/infra/bus/service/api/BusArrivalInfoService.java
  src/main/java/com/dku/council/infra/bus/service/provider/BusArrivalProvider.java
  src/main/java/com/dku/council/infra/bus/service/provider/GGBusProvider.java
  src/main/java/com/dku/council/infra/bus/service/provider/ShuttleBusProvider.java
  src/main/java/com/dku/council/infra/bus/service/provider/ShuttleTimeTable.java
  src/main/java/com/dku/council/infra/bus/service/provider/TownBusProvider.java
  src/main/resources/shuttle_time.table
  src/test/java/com/dku/council/domain/bus/repository/impl/BusArrivalMemoryRepositoryTest.java
  src/test/java/com/dku/council/domain/bus/service/BusServiceTest.java
  src/test/java/com/dku/council/domain/like/repository/impl/PostLikeRedisRepositoryTest.java
  src/test/java/com/dku/council/domain/post/controller/NewsControllerTest.java
  src/test/java/com/dku/council/domain/post/controller/PetitionControllerTest.java
  src/test/java/com/dku/council/domain/post/repository/impl/ViewCountRedisRepositoryTest.java
  src/test/java/com/dku/council/domain/post/service/ViewCountServiceTest.java
  src/test/java/com/dku/council/infra/bus/service/OpenApiBusServiceTest.java
  src/test/java/com/dku/council/infra/bus/service/provider/GGBusProviderTest.java
  src/test/java/com/dku/council/infra/bus/service/provider/ShuttleBusProviderTest.java
  src/test/java/com/dku/council/infra/bus/service/provider/ShuttleTimeTableTest.java
  src/test/java/com/dku/council/infra/bus/service/provider/TownBusProviderTest.java
  src/test/java/com/dku/council/infra/dku/service/DkuAuthenticationServiceTest.java
  src/test/java/com/dku/council/infra/dku/service/DkuCrawlerServiceTest.java
  src/test/java/com/dku/council/infra/nhn/service/NHNAuthServiceTest.java
  src/test/java/com/dku/council/infra/nhn/service/ObjectStorageServiceTest.java
  src/test/java/com/dku/council/infra/nhn/service/SMSServiceTest.java
  src/test/java/com/dku/council/mock/ServerMock.java
  src/test/java/com/dku/council/util/ClockUtil.java
  src/test/java/com/dku/council/util/MvcMockResponse.java
  src/test/java/com/dku/council/util/OnlyDevTest.java
  src/test/java/com/dku/council/util/PropertiesBase64Encoder.java
  src/test/java/com/dku/council/util/ResourceUtil.java
  src/test/java/com/dku/council/util/base/AbstractContainerRedisTest.java
  src/test/java/com/dku/council/util/base/AbstractMockServerTest.java
Labels: feat

#83 개발 서버에 배포
  src/main/java/com/dku/council/domain/bus/model/Bus.java
  src/main/java/com/dku/council/domain/bus/model/BusStation.java
  src/main/java/com/dku/council/domain/like/PostLikeService.java
  src/main/java/com/dku/council/domain/user/controller/EmailController.java
  src/main/java/com/dku/council/domain/user/exception/WrongEmailCodeException.java
  src/main/java/com/dku/council/domain/user/model/dto/request/RequestSendEmailCode.java
  src/main/java/com/dku/council/domain/user/model/dto/request/RequestVerifyEmailCodeDto.java
  src/main/java/com/dku/council/domain/user/service/DkuEmailService.java
  src/main/java/com/dku/council/global/util/TextTemplateEngine.java
  src/main/java/com/dku/council/infra/bus/model/BusStatus.java
  src/main/java/com/dku/council/infra/bus/service/OpenApiBusService.java
  src/main/java/com/dku/council/infra/bus/service/api/BusArrivalInfoService.java
  src/main/java/com/dku/council/infra/bus/service/provider/BusArrivalProvider.java
  src/main/java/com/dku/council/infra/bus/service/provider/GGBusProvider.java
  src/main/java/com/dku/council/infra/bus/service/provider/ShuttleBusProvider.java
  src/main/java/com/dku/council/infra/bus/service/provider/ShuttleTimeTable.java
  src/main/java/com/dku/council/infra/bus/service/provider/TownBusProvider.java
  src/main/java/com/dku/council/infra/nhn/model/dto/NhnMessage.java
  src/main/java/com/dku/council/infra/nhn/service/NHNEmailService.java
  src/main/java/com/dku/council/infra/nhn/service/impl/NHNEmailServiceImpl.java
  src/main/resources/auth_email_content.html
  src/main/resources/errors.properties
  src/main/resources/shuttle_time.table
  src/test/java/com/dku/council/domain/bus/repository/impl/BusArrivalMemoryRepositoryTest.java
  src/test/java/com/dku/council/domain/bus/service/BusServiceTest.java
  src/test/java/com/dku/council/domain/like/repository/impl/PostLikeRedisRepositoryTest.java
  src/test/java/com/dku/council/domain/post/controller/NewsControllerTest.java
  src/test/java/com/dku/council/domain/post/controller/PetitionControllerTest.java
  src/test/java/com/dku/council/domain/post/repository/impl/ViewCountRedisRepositoryTest.java
  src/test/java/com/dku/council/domain/post/service/ViewCountServiceTest.java
  src/test/java/com/dku/council/infra/bus/service/OpenApiBusServiceTest.java
  src/test/java/com/dku/council/infra/bus/service/provider/GGBusProviderTest.java
  src/test/java/com/dku/council/infra/bus/service/provider/ShuttleBusProviderTest.java
  src/test/java/com/dku/council/infra/bus/service/provider/ShuttleTimeTableTest.java
  src/test/java/com/dku/council/infra/bus/service/provider/TownBusProviderTest.java
  src/test/java/com/dku/council/infra/dku/service/DkuAuthenticationServiceTest.java
  src/test/java/com/dku/council/infra/dku/service/DkuCrawlerServiceTest.java
  src/test/java/com/dku/council/infra/nhn/service/NHNAuthServiceTest.java
  src/test/java/com/dku/council/infra/nhn/service/ObjectStorageServiceTest.java
  src/test/java/com/dku/council/infra/nhn/service/SMSServiceTest.java
  src/test/java/com/dku/council/mock/ServerMock.java
  src/test/java/com/dku/council/util/ClockUtil.java
  src/test/java/com/dku/council/util/MvcMockResponse.java
  src/test/java/com/dku/council/util/OnlyDevTest.java
  src/test/java/com/dku/council/util/PropertiesBase64Encoder.java
  src/test/java/com/dku/council/util/ResourceUtil.java
  src/test/java/com/dku/council/util/base/AbstractContainerRedisTest.java
  src/test/java/com/dku/council/util/base/AbstractMockServerTest.java
Labels: deploy

#84 테스트 수정
  src/test/java/com/dku/council/infra/bus/service/provider/ShuttleBusProviderTest.java
Labels: bug

#85 개발 서버에 배포
  src/test/java/com/dku/council/infra/bus/service/provider/ShuttleBusProviderTest.java
Labels: deploy

#86 버스 도착정보 버그 수정
  src/main/java/com/dku/council/domain/bus/model/Bus.java
  src/main/java/com/dku/council/infra/bus/model/BusArrival.java
  src/main/java/com/dku/council/infra/bus/model/mapper/BusResponseMapper.java
  src/main/java/com/dku/council/infra/bus/service/OpenApiBusService.java
  src/main/java/com/dku/council/infra/bus/service/provider/GGBusProvider.java
  src/main/java/com/dku/council/infra/bus/service/provider/ShuttleBusProvider.java
  src/main/java/com/dku/council/infra/bus/service/provider/TownBusProvider.java
  src/test/java/com/dku/council/infra/bus/service/OpenApiBusServiceTest.java
  src/test/java/com/dku/council/infra/bus/service/provider/ShuttleBusProviderTest.java
  src/test/java/com/dku/council/mock/BusArrivalMock.java
Labels: bug

#87 개발 서버에 배포
  src/main/java/com/dku/council/domain/bus/model/Bus.java
  src/main/java/com/dku/council/infra/bus/model/BusArrival.java
  src/main/java/com/dku/council/infra/bus/model/mapper/BusResponseMapper.java
  src/main/java/com/dku/council/infra/bus/service/OpenApiBusService.java
  src/main/java/com/dku/council/infra/bus/service/provider/GGBusProvider.java
  src/main/java/com/dku/council/infra/bus/service/provider/ShuttleBusProvider.java
  src/main/java/com/dku/council/infra/bus/service/provider/TownBusProvider.java
  src/test/java/com/dku/council/infra/bus/service/OpenApiBusServiceTest.java
  src/test/java/com/dku/council/infra/bus/service/provider/ShuttleBusProviderTest.java
  src/test/java/com/dku/council/mock/BusArrivalMock.java
Labels: deploy

#96 Major를 DB로 이동
  docs/images/domain_model.png
  docs/images/erd.png
  src/main/java/com/dku/council/domain/comment/model/dto/CommentDto.java
  src/main/java/com/dku/council/domain/comment/service/CommentService.java
  src/main/java/com/dku/council/domain/post/controller/RuleController.java
  src/main/java/com/dku/council/domain/post/model/dto/list/SummarizedRuleDto.java
  src/main/java/com/dku/council/domain/post/repository/GenericPostRepository.java
  src/main/java/com/dku/council/domain/post/repository/PostRepository.java
  src/main/java/com/dku/council/domain/post/service/GenericPostService.java
  src/main/java/com/dku/council/domain/rental/repository/RentalItemRepository.java
  src/main/java/com/dku/council/domain/rental/repository/RentalRepository.java
  src/main/java/com/dku/council/domain/rental/service/RentalItemService.java
  src/main/java/com/dku/council/domain/rental/service/RentalService.java
  src/main/java/com/dku/council/domain/user/controller/DKUController.java
  src/main/java/com/dku/council/domain/user/controller/EmailController.java
  src/main/java/com/dku/council/domain/user/controller/UserController.java
  src/main/java/com/dku/council/domain/user/exception/MajorNotFoundException.java
  src/main/java/com/dku/council/domain/user/model/Department.java
  src/main/java/com/dku/council/domain/user/model/MajorData.java
  src/main/java/com/dku/council/domain/user/model/dto/request/RequestVerifyEmailCodeDto.java
  src/main/java/com/dku/council/domain/user/model/dto/response/ResponseLoginDto.java
  src/main/java/com/dku/council/domain/user/model/dto/response/ResponseMajorDto.java
  src/main/java/com/dku/council/domain/user/model/dto/response/ResponseScrappedStudentInfoDto.java
  src/main/java/com/dku/council/domain/user/model/entity/Major.java
  src/main/java/com/dku/council/domain/user/model/entity/User.java
  src/main/java/com/dku/council/domain/user/repository/MajorRepository.java
  src/main/java/com/dku/council/domain/user/service/DKUAuthService.java
  src/main/java/com/dku/council/domain/user/service/DkuEmailService.java
  src/main/java/com/dku/council/domain/user/service/UserService.java
  src/main/java/com/dku/council/infra/dku/model/StudentInfo.java
  src/main/java/com/dku/council/infra/dku/service/DkuCrawlerService.java
  src/main/resources/majors.properties
  src/test/java/com/dku/council/domain/comment/service/CommentServiceTest.java
  src/test/java/com/dku/council/domain/like/PostLikeServiceTest.java
  src/test/java/com/dku/council/domain/post/controller/NewsControllerTest.java
  src/test/java/com/dku/council/domain/post/controller/PetitionControllerTest.java
  src/test/java/com/dku/council/domain/post/controller/VocControllerTest.java
  src/test/java/com/dku/council/domain/post/repository/spec/PostSpecTest.java
  src/test/java/com/dku/council/domain/post/service/GenericPostServiceTest.java
  src/test/java/com/dku/council/domain/rental/controller/RentalControllerTest.java
  src/test/java/com/dku/council/domain/rental/repository/spec/RentalSpecTest.java
  src/test/java/com/dku/council/domain/rental/service/RentalServiceTest.java
  src/test/java/com/dku/council/domain/tag/service/TagServiceTest.java
  src/test/java/com/dku/council/domain/user/DepartmentTest.java
  src/test/java/com/dku/council/domain/user/MajorDataTest.java
  src/test/java/com/dku/council/domain/user/repository/MajorRepositoryTest.java
  src/test/java/com/dku/council/infra/dku/service/DkuCrawlerServiceTest.java
  src/test/java/com/dku/council/mock/CommentMock.java
  src/test/java/com/dku/council/mock/MajorMock.java
  src/test/java/com/dku/council/mock/NewsMock.java
  src/test/java/com/dku/council/mock/RentalItemMock.java
  src/test/java/com/dku/council/mock/RentalMock.java
  src/test/java/com/dku/council/mock/UserMock.java
  src/test/resources/majors.properties
  src/test/resources/mockdata/dku/student-info-response-failed-1.html
  src/test/resources/mockdata/dku/student-info-response-failed-2.html
Labels: refactor

#98 대여, 회원가입, SMS인증 시 사전 check 로직 추가
  src/main/java/com/dku/council/domain/rental/exception/AlreadyRentalException.java
  src/main/java/com/dku/council/domain/rental/repository/RentalRepository.java
  src/main/java/com/dku/council/domain/rental/service/RentalService.java
  src/main/java/com/dku/council/domain/user/controller/UserController.java
  src/main/java/com/dku/council/domain/user/exception/AlreadyPhoneException.java
  src/main/java/com/dku/council/domain/user/exception/AlreadyStudentIdException.java
  src/main/java/com/dku/council/domain/user/model/dto/request/RequestLoginDto.java
  src/main/java/com/dku/council/domain/user/model/dto/request/RequestSignupDto.java
  src/main/java/com/dku/council/domain/user/model/dto/request/RequestVerifyStudentDto.java
  src/main/java/com/dku/council/domain/user/repository/UserRepository.java
  src/main/java/com/dku/council/domain/user/repository/impl/SignupAuthRedisRepository.java
  src/main/java/com/dku/council/domain/user/service/DKUAuthService.java
  src/main/java/com/dku/council/domain/user/service/DkuEmailService.java
  src/main/java/com/dku/council/domain/user/service/SMSVerificationService.java
  src/main/java/com/dku/council/domain/user/service/SignupService.java
  src/main/java/com/dku/council/domain/user/service/UserService.java
  src/main/resources/errors.properties
  src/test/java/com/dku/council/domain/rental/controller/RentalControllerTest.java
  src/test/java/com/dku/council/domain/rental/service/RentalServiceTest.java
  src/test/java/com/dku/council/domain/user/repository/impl/SignupAuthRedisRepositoryTest.java
  src/test/java/com/dku/council/domain/user/service/DKUAuthServiceTest.java
  src/test/java/com/dku/council/domain/user/service/SMSVerificationServiceTest.java
  src/test/java/com/dku/council/domain/user/service/SignupServiceTest.java
  src/test/java/com/dku/council/domain/user/service/UserServiceTest.java
  src/test/java/com/dku/council/mock/UserMock.java
  src/test/resources/errors.properties
Labels: bug

#100 버스 예측 기능 추가
  src/main/java/com/dku/council/domain/bus/model/Bus.java
  src/main/java/com/dku/council/domain/bus/model/BusStation.java
  src/main/java/com/dku/council/infra/bus/model/BusArrival.java
  src/main/java/com/dku/council/infra/bus/model/BusStatus.java
  src/main/java/com/dku/council/infra/bus/model/ResponseGGBusArrival.java
  src/main/java/com/dku/council/infra/bus/model/ResponseKakaoBusApi.java
  src/main/java/com/dku/council/infra/bus/model/mapper/BusResponseMapper.java
  src/main/java/com/dku/council/infra/bus/predict/BusArrivalPredictService.java
  src/main/java/com/dku/council/infra/bus/predict/impl/BusTimeTablePredictService.java
  src/main/java/com/dku/council/infra/bus/predict/impl/TimeTable.java
  src/main/java/com/dku/council/infra/bus/predict/impl/TimeTableParser.java
  src/main/java/com/dku/council/infra/bus/provider/BusArrivalProvider.java
  src/main/java/com/dku/council/infra/bus/provider/GGBusProvider.java
  src/main/java/com/dku/council/infra/bus/provider/ShuttleBusProvider.java
  src/main/java/com/dku/council/infra/bus/provider/TownBusProvider.java
  src/main/java/com/dku/council/infra/bus/service/OpenApiBusService.java
  src/main/java/com/dku/council/infra/bus/service/provider/ShuttleBusProvider.java
  src/main/java/com/dku/council/infra/bus/service/provider/ShuttleTimeTable.java
  src/main/resources/bustable/weekday/bearstatue/24.table
  src/main/resources/bustable/weekday/bearstatue/720-3.table
  src/main/resources/bustable/weekday/bearstatue/shuttle-bus.table
  src/main/resources/bustable/weekday/dkugate/102.table
  src/main/resources/bustable/weekday/dkugate/1101.table
  src/main/resources/bustable/weekday/dkugate/1101N.table
  src/main/resources/bustable/weekday/dkugate/24.table
  src/main/resources/bustable/weekday/dkugate/7007-1.table
  src/main/resources/bustable/weekday/dkugate/720-3.table
  src/main/resources/bustable/weekday/dkugate/8100.table
  src/main/resources/bustable/weekday/dkugate/shuttle-bus.table
  src/main/resources/bustable/weekend/bearstatue/24.table
  src/main/resources/bustable/weekend/bearstatue/720-3.table
  src/main/resources/bustable/weekend/bearstatue/shuttle-bus.table
  src/main/resources/bustable/weekend/dkugate/102.table
  src/main/resources/bustable/weekend/dkugate/1101.table
  src/main/resources/bustable/weekend/dkugate/1101N.table
  src/main/resources/bustable/weekend/dkugate/24.table
  src/main/resources/bustable/weekend/dkugate/7007-1.table
  src/main/resources/bustable/weekend/dkugate/720-3.table
  src/main/resources/bustable/weekend/dkugate/8100.table
  src/main/resources/bustable/weekend/dkugate/shuttle-bus.table
  src/test/java/com/dku/council/domain/rental/repository/spec/RentalSpecTest.java
  src/test/java/com/dku/council/domain/rental/service/RentalItemServiceTest.java
  src/test/java/com/dku/council/domain/user/repository/MajorRepositoryTest.java
  src/test/java/com/dku/council/infra/bus/predict/impl/BusTimeTablePredictServiceTest.java
  src/test/java/com/dku/council/infra/bus/predict/impl/TimeTableParserTest.java
  src/test/java/com/dku/council/infra/bus/predict/impl/TimeTableTest.java
  src/test/java/com/dku/council/infra/bus/provider/GGBusProviderTest.java
  src/test/java/com/dku/council/infra/bus/provider/ShuttleBusProviderTest.java
  src/test/java/com/dku/council/infra/bus/provider/TownBusProviderTest.java
  src/test/java/com/dku/council/infra/bus/service/OpenApiBusServiceTest.java
  src/test/java/com/dku/council/infra/bus/service/provider/ShuttleBusProviderTest.java
  src/test/java/com/dku/council/mock/BusArrivalMock.java
  src/test/java/com/dku/council/mock/NewsMock.java
  src/test/java/com/dku/council/mock/RentalItemMock.java
  src/test/java/com/dku/council/mock/RentalMock.java
  src/test/java/com/dku/council/util/EntityUtil.java
  src/test/java/com/dku/council/util/FieldInjector.java
  src/test/java/com/dku/council/util/FieldReflector.java
  src/test/resources/mockdata/bus/test-bus.table
Labels: feat

#103 셔틀버스 주말에는 STOP
  src/main/java/com/dku/council/domain/post/controller/RuleController.java
  src/main/java/com/dku/council/domain/user/controller/UserController.java
  src/main/java/com/dku/council/domain/user/model/dto/request/RequestSignupDto.java
  src/main/java/com/dku/council/domain/user/model/entity/User.java
  src/main/java/com/dku/council/domain/user/service/SignupService.java
  src/main/java/com/dku/council/infra/bus/exception/CannotGetTimeTable.java
  src/main/java/com/dku/council/infra/bus/predict/impl/BusTimeTablePredictService.java
  src/main/java/com/dku/council/infra/bus/predict/impl/TimeTableParser.java
  src/main/resources/bustable/weekend/bearstatue/shuttle-bus.table
  src/main/resources/bustable/weekend/dkugate/shuttle-bus.table
  src/main/resources/errors.properties
  src/test/java/com/dku/council/domain/rental/controller/RentalControllerTest.java
  src/test/java/com/dku/council/domain/user/service/SignupServiceTest.java
  src/test/java/com/dku/council/mock/UserMock.java
  src/test/resources/errors.properties
Labels: bug

#113 Rule 일부 수정
  docs/rules.md
Labels: docs

#111 좋아요 API 추가
  src/main/java/com/dku/council/domain/bus/model/CachedBusArrivals.java
  src/main/java/com/dku/council/domain/bus/model/repository/CachedBusArrivals.java
  src/main/java/com/dku/council/domain/bus/repository/BusArrivalMemoryRepository.java
  src/main/java/com/dku/council/domain/bus/repository/BusArrivalRepository.java
  src/main/java/com/dku/council/domain/bus/repository/impl/BusArrivalMemoryRepositoryImpl.java
  src/main/java/com/dku/council/domain/bus/repository/impl/BusArrivalRedisRepository.java
  src/main/java/com/dku/council/domain/bus/service/BusArrivalScheduler.java
  src/main/java/com/dku/council/domain/bus/service/BusService.java
  src/main/java/com/dku/council/domain/like/PostLikeService.java
  src/main/java/com/dku/council/domain/page/model/dto/response/CarouselImageResponse.java
  src/main/java/com/dku/council/domain/page/service/PageServiceImpl.java
  src/main/java/com/dku/council/domain/post/config/PostConfig.java
  src/main/java/com/dku/council/domain/post/controller/ConferenceController.java
  src/main/java/com/dku/council/domain/post/controller/GeneralForumController.java
  src/main/java/com/dku/council/domain/post/controller/NewsController.java
  src/main/java/com/dku/council/domain/post/controller/PetitionController.java
  src/main/java/com/dku/council/domain/post/controller/RuleController.java
  src/main/java/com/dku/council/domain/post/controller/VocController.java
  src/main/java/com/dku/council/domain/post/model/PostStatus.java
  src/main/java/com/dku/council/domain/post/model/dto/list/SummarizedConferenceDto.java
  src/main/java/com/dku/council/domain/post/model/dto/list/SummarizedGeneralForumDto.java
  src/main/java/com/dku/council/domain/post/model/dto/list/SummarizedGenericPostDto.java
  src/main/java/com/dku/council/domain/post/model/dto/list/SummarizedPetitionDto.java
  src/main/java/com/dku/council/domain/post/model/dto/list/SummarizedRuleDto.java
  src/main/java/com/dku/council/domain/post/model/dto/list/SummarizedVocDto.java
  src/main/java/com/dku/council/domain/post/model/dto/response/ResponsePetitionDto.java
  src/main/java/com/dku/council/domain/post/model/dto/response/ResponseSingleGenericPostDto.java
  src/main/java/com/dku/council/domain/post/model/dto/response/ResponseVocDto.java
  src/main/java/com/dku/council/domain/post/repository/ViewCountMemoryRepository.java
  src/main/java/com/dku/council/domain/post/repository/impl/ViewCountRedisRepository.java
  src/main/java/com/dku/council/domain/post/service/GenericPostService.java
  src/main/java/com/dku/council/domain/post/service/PetitionService.java
  src/main/java/com/dku/council/domain/post/service/ViewCountService.java
  src/main/java/com/dku/council/domain/post/service/VocService.java
  src/main/java/com/dku/council/domain/user/controller/UserController.java
  src/main/java/com/dku/council/domain/user/model/dto/request/RequestSignupDto.java
  src/main/java/com/dku/council/domain/user/repository/impl/SignupAuthRedisRepository.java
  src/main/java/com/dku/council/domain/user/service/UserFindService.java
  src/main/java/com/dku/council/global/auth/jwt/JwtProvider.java
  src/main/java/com/dku/council/global/base/AbstractKeyValueCacheRepository.java
  src/main/java/com/dku/council/global/component/model/CacheObject.java
  src/main/java/com/dku/council/infra/bus/model/BusArrival.java
  src/main/java/com/dku/council/infra/nhn/service/impl/FileUploadServiceImpl.java
  src/test/java/com/dku/council/domain/bus/repository/impl/BusArrivalMemoryRepositoryTest.java
  src/test/java/com/dku/council/domain/bus/service/BusServiceTest.java
  src/test/java/com/dku/council/domain/like/PostLikeServiceTest.java
  src/test/java/com/dku/council/domain/page/service/PageServiceTest.java
  src/test/java/com/dku/council/domain/post/repository/impl/ViewCountRedisRepositoryTest.java
  src/test/java/com/dku/council/domain/post/service/GenericPostServiceTest.java
  src/test/java/com/dku/council/domain/post/service/ViewCountServiceTest.java
  src/test/java/com/dku/council/domain/user/repository/impl/SignupAuthRedisRepositoryTest.java
  src/test/java/com/dku/council/domain/user/service/DKUAuthServiceTest.java
  src/test/java/com/dku/council/domain/user/service/SMSVerificationServiceTest.java
  src/test/java/com/dku/council/mock/NewsMock.java
  src/test/java/com/dku/council/mock/PetitionMock.java
Labels: feat

#119 청원 만료 scheduler 추가
  src/main/java/com/dku/council/domain/bus/scheduler/BusArrivalScheduler.java
  src/main/java/com/dku/council/domain/like/model/entity/PostLike.java
  src/main/java/com/dku/council/domain/like/repository/PostLikePersistenceRepository.java
  src/main/java/com/dku/council/domain/like/scheduler/PostLikeDumpScheduler.java
  src/main/java/com/dku/council/domain/like/service/PostLikeService.java
  src/main/java/com/dku/council/domain/post/config/PostConfig.java
  src/main/java/com/dku/council/domain/post/controller/GeneralForumController.java
  src/main/java/com/dku/council/domain/post/controller/NewsController.java
  src/main/java/com/dku/council/domain/post/controller/PetitionController.java
  src/main/java/com/dku/council/domain/post/controller/VocController.java
  src/main/java/com/dku/council/domain/post/model/PetitionStatus.java
  src/main/java/com/dku/council/domain/post/model/entity/Post.java
  src/main/java/com/dku/council/domain/post/model/entity/posttype/Petition.java
  src/main/java/com/dku/council/domain/post/repository/PetitionRepository.java
  src/main/java/com/dku/council/domain/post/scheduler/PetitionStatusScheduler.java
  src/main/java/com/dku/council/domain/post/service/GenericPostService.java
  src/main/java/com/dku/council/domain/user/controller/UserController.java
  src/main/java/com/dku/council/infra/bus/service/OpenApiBusService.java
  src/test/java/com/dku/council/domain/like/service/PostLikeServiceTest.java
  src/test/java/com/dku/council/domain/post/repository/PetitionRepositoryTest.java
  src/test/java/com/dku/council/domain/post/service/GenericPostServiceTest.java
  src/test/java/com/dku/council/infra/bus/service/OpenApiBusServiceTest.java
  src/test/java/com/dku/council/mock/PetitionMock.java
Labels: feat

#122 개발 서버에 배포
  .github/workflows/dev_cd.yml
Labels: deploy

#128 CreatedAt으로 필드 통일
  src/main/java/com/dku/council/domain/comment/model/dto/CommentDto.java
  src/main/java/com/dku/council/domain/post/model/dto/list/SummarizedGenericPostDto.java
  src/test/java/com/dku/council/domain/post/repository/PetitionRepositoryTest.java
  src/test/java/com/dku/council/domain/post/service/GenericPostServiceTest.java
Labels: bug

#129 개발 서버에 배포
  src/main/java/com/dku/council/domain/comment/model/dto/CommentDto.java
  src/main/java/com/dku/council/domain/post/model/dto/list/SummarizedGenericPostDto.java
  src/test/java/com/dku/council/domain/post/repository/PetitionRepositoryTest.java
  src/test/java/com/dku/council/domain/post/service/GenericPostServiceTest.java
Labels: bug, deploy

#124 청원 dto 수정
  src/main/java/com/dku/council/domain/post/controller/PetitionController.java
  src/main/java/com/dku/council/domain/post/model/dto/list/SummarizedGenericPostDto.java
  src/main/java/com/dku/council/domain/post/model/dto/list/SummarizedPetitionDto.java
  src/main/java/com/dku/council/domain/post/model/dto/response/ResponsePetitionDto.java
  src/main/java/com/dku/council/domain/post/repository/spec/PostSpec.java
  src/main/java/com/dku/council/domain/post/service/PetitionService.java
  src/test/java/com/dku/council/domain/post/controller/PetitionControllerTest.java
  src/test/java/com/dku/council/domain/post/service/GenericPostServiceTest.java
Labels: update

#130 개발 서버에 배포
  src/main/java/com/dku/council/domain/bus/service/BusService.java
  src/main/java/com/dku/council/domain/comment/model/dto/CommentDto.java
  src/main/java/com/dku/council/domain/post/controller/PetitionController.java
  src/main/java/com/dku/council/domain/post/model/dto/list/SummarizedGenericPostDto.java
  src/main/java/com/dku/council/domain/post/model/dto/list/SummarizedPetitionDto.java
  src/main/java/com/dku/council/domain/post/model/dto/response/ResponsePetitionDto.java
  src/main/java/com/dku/council/domain/post/repository/spec/PostSpec.java
  src/main/java/com/dku/council/domain/post/service/PetitionService.java
  src/main/java/com/dku/council/infra/bus/service/OpenApiBusService.java
  src/main/resources/bustable/weekday/bearstatue/720-3.table
  src/main/resources/bustable/weekday/dkugate/1101.table
  src/main/resources/bustable/weekday/dkugate/720-3.table
  src/test/java/com/dku/council/domain/bus/service/BusServiceTest.java
  src/test/java/com/dku/council/domain/post/controller/PetitionControllerTest.java
  src/test/java/com/dku/council/domain/post/service/GenericPostServiceTest.java
  src/test/java/com/dku/council/infra/bus/service/OpenApiBusServiceTest.java
  src/test/java/com/dku/council/mock/BusArrivalMock.java
Labels: deploy

#131 dev_cd network 변경
  .github/workflows/dev_cd.yml
Labels: bug

#132 개발 서버로 배포
  .github/workflows/dev_cd.yml
Labels: bug, deploy

#135 JavadocPropertyCustomizer 조건부 로딩
  src/main/java/com/dku/council/global/config/swagger/JavadocPropertyCustomizer.java
Labels: bug

#136 Table 없을 때 발생하는 오류 mute
  src/main/java/com/dku/council/infra/bus/predict/impl/BusTimeTablePredictService.java
Labels: update

#137 운영 서버에 배포
  src/main/java/com/dku/council/global/config/swagger/JavadocPropertyCustomizer.java
  src/main/java/com/dku/council/infra/bus/predict/impl/BusTimeTablePredictService.java
Labels: deploy

#138 Hotfix dev에 반영
  .github/workflows/dev_cd.yml
  src/main/java/com/dku/council/global/config/swagger/JavadocPropertyCustomizer.java
  src/main/java/com/dku/council/infra/bus/predict/impl/BusTimeTablePredictService.java
  src/test/java/com/dku/council/domain/rental/controller/RentalControllerTest.java
Labels: chore

#139 pinpoint agent 설치
  .github/workflows/dev_cd.yml
  Dockerfile
Labels: chore

#140 개발 서버에 배포
  .github/workflows/dev_cd.yml
  Dockerfile
  src/main/java/com/dku/council/domain/post/model/dto/response/ResponseSingleGenericPostDto.java
  src/main/java/com/dku/council/domain/post/model/entity/Post.java
  src/main/java/com/dku/council/domain/post/model/entity/posttype/Conference.java
  src/main/java/com/dku/council/domain/post/model/entity/posttype/GeneralForum.java
  src/main/java/com/dku/council/domain/post/model/entity/posttype/News.java
  src/main/java/com/dku/council/domain/post/model/entity/posttype/Petition.java
  src/main/java/com/dku/council/domain/post/model/entity/posttype/Rule.java
  src/main/java/com/dku/council/domain/post/model/entity/posttype/Voc.java
  src/test/java/com/dku/council/domain/post/service/GenericPostServiceTest.java
Labels: deploy

#141 Docker file 오류 수정
  Dockerfile
Labels: bug, deploy

#142 Docker file 개선
  .github/workflows/dev_cd.yml
  Dockerfile
Labels: deploy

#143 운영 서버에 배포
  Dockerfile
  src/main/java/com/dku/council/domain/post/model/dto/response/ResponseSingleGenericPostDto.java
  src/main/java/com/dku/council/domain/post/model/entity/Post.java
  src/main/java/com/dku/council/domain/post/model/entity/posttype/Conference.java
  src/main/java/com/dku/council/domain/post/model/entity/posttype/GeneralForum.java
  src/main/java/com/dku/council/domain/post/model/entity/posttype/News.java
  src/main/java/com/dku/council/domain/post/model/entity/posttype/Petition.java
  src/main/java/com/dku/council/domain/post/model/entity/posttype/Rule.java
  src/main/java/com/dku/council/domain/post/model/entity/posttype/Voc.java
  src/test/java/com/dku/council/domain/post/service/GenericPostServiceTest.java
Labels: chore

#144 Docker file agent name 명시
  .github/workflows/dev_cd.yml
  .github/workflows/prod_cd.yml
  Dockerfile
Labels: chore, deploy

#145 Docker file shell form으로 변경
  .github/workflows/dev_cd.yml
  .github/workflows/prod_cd.yml
  Dockerfile
Labels: chore, deploy

#146 운영 서버에 배포
  .github/workflows/dev_cd.yml
  .github/workflows/prod_cd.yml
  Dockerfile
Labels: chore, deploy

#147 Pinpoint 셋업
  .github/workflows/dev_cd.yml
  .github/workflows/prod_cd.yml
  Dockerfile
Labels: chore

#156 조회수 관련 버그 수정
  src/main/java/com/dku/council/domain/post/controller/GeneralForumController.java
  src/main/java/com/dku/council/domain/post/controller/NewsController.java
  src/main/java/com/dku/council/domain/post/controller/PetitionController.java
  src/main/java/com/dku/council/domain/post/controller/RuleController.java
  src/main/java/com/dku/council/domain/post/controller/VocController.java
  src/main/java/com/dku/council/global/util/RemoteAddressUtil.java
Labels: bug

#158 @Transactional 추가
  src/main/java/com/dku/council/domain/like/service/PostLikeService.java
Labels: bug

#159 개발 서버에 배포
  src/main/java/com/dku/council/domain/like/service/PostLikeService.java
Labels: deploy

#168 DTO 수정
  src/main/java/com/dku/council/domain/comment/model/dto/CommentDto.java
  src/main/java/com/dku/council/domain/comment/service/CommentService.java
  src/main/java/com/dku/council/domain/post/controller/GeneralForumController.java
  src/main/java/com/dku/council/domain/post/controller/PetitionController.java
  src/main/java/com/dku/council/domain/post/model/dto/list/SummarizedGeneralForumDto.java
  src/main/java/com/dku/council/domain/post/model/dto/list/SummarizedPetitionDto.java
  src/main/java/com/dku/council/domain/post/service/PetitionService.java
  src/test/java/com/dku/council/domain/post/service/GenericPostServiceTest.java
Labels: update

#169 버스 API 개선
  src/main/java/com/dku/council/infra/bus/predict/impl/BusTimeTablePredictService.java
Labels: bug, update

#170 일부 코드 리팩토링
  src/main/java/com/dku/council/domain/post/config/PostConfig.java
  src/main/java/com/dku/council/domain/post/model/entity/Post.java
  src/main/java/com/dku/council/domain/post/model/entity/posttype/Conference.java
  src/main/java/com/dku/council/domain/post/model/entity/posttype/GeneralForum.java
  src/main/java/com/dku/council/domain/post/model/entity/posttype/News.java
  src/main/java/com/dku/council/domain/post/model/entity/posttype/Rule.java
  src/main/java/com/dku/council/domain/post/model/entity/posttype/Voc.java
  src/main/java/com/dku/council/domain/post/repository/PetitionRepository.java
  src/main/java/com/dku/council/domain/rental/model/entity/RentalItem.java
  src/main/java/com/dku/council/domain/user/controller/UserController.java
  src/main/java/com/dku/council/domain/user/model/entity/User.java
Labels: bug, refactor

#172 운영 서버에 배포
  src/main/java/com/dku/council/domain/comment/model/dto/CommentDto.java
  src/main/java/com/dku/council/domain/comment/service/CommentService.java
  src/main/java/com/dku/council/domain/post/config/PostConfig.java
  src/main/java/com/dku/council/domain/post/controller/GeneralForumController.java
  src/main/java/com/dku/council/domain/post/controller/PetitionController.java
  src/main/java/com/dku/council/domain/post/model/dto/list/SummarizedGeneralForumDto.java
  src/main/java/com/dku/council/domain/post/model/dto/list/SummarizedPetitionDto.java
  src/main/java/com/dku/council/domain/post/model/entity/Post.java
  src/main/java/com/dku/council/domain/post/model/entity/posttype/Conference.java
  src/main/java/com/dku/council/domain/post/model/entity/posttype/GeneralForum.java
  src/main/java/com/dku/council/domain/post/model/entity/posttype/News.java
  src/main/java/com/dku/council/domain/post/model/entity/posttype/Rule.java
  src/main/java/com/dku/council/domain/post/model/entity/posttype/Voc.java
  src/main/java/com/dku/council/domain/post/repository/PetitionRepository.java
  src/main/java/com/dku/council/domain/post/service/PetitionService.java
  src/main/java/com/dku/council/domain/rental/model/entity/RentalItem.java
  src/main/java/com/dku/council/domain/user/controller/UserController.java
  src/main/java/com/dku/council/domain/user/model/entity/User.java
  src/main/java/com/dku/council/infra/bus/predict/impl/BusTimeTablePredictService.java
  src/test/java/com/dku/council/domain/post/service/GenericPostServiceTest.java
Labels: deploy

#181 버스, 댓글 버그 수정
  src/main/java/com/dku/council/domain/comment/CommentRepository.java
  src/main/java/com/dku/council/domain/comment/service/CommentService.java
  src/main/java/com/dku/council/domain/post/repository/GenericPostRepository.java
  src/main/java/com/dku/council/infra/bus/model/mapper/BusResponseMapper.java
  src/main/java/com/dku/council/infra/bus/provider/GGBusProvider.java
  src/test/java/com/dku/council/domain/comment/CommentRepositoryTest.java
  src/test/java/com/dku/council/domain/comment/service/CommentServiceTest.java
  src/test/java/com/dku/council/infra/bus/provider/TownBusProviderTest.java
  src/test/java/com/dku/council/mock/CommentMock.java
  src/test/java/com/dku/council/mock/GeneralForumMock.java
  src/test/resources/mockdata/bus/getBusArrivalList.xml
  src/test/resources/mockdata/bus/kakao.json
Labels: bug

#187 태그 네임 중복 제거
  src/main/java/com/dku/council/domain/tag/model/entity/Tag.java
  src/main/java/com/dku/council/global/error/ControllerAdvisor.java
  src/main/java/com/dku/council/global/error/exception/DuplicateDataException.java
  src/main/resources/errors.properties
  src/test/java/com/dku/council/domain/tag/repository/TagRepositoryTest.java
  src/test/java/com/dku/council/domain/tag/service/TagServiceTest.java
  src/test/java/com/dku/council/mock/TagMock.java
  src/test/resources/errors.properties
Labels: bug

#192 전화번호 변경 추가.
  src/main/java/com/dku/council/domain/user/controller/UserController.java
  src/main/java/com/dku/council/domain/user/model/dto/request/RequestSendPasswordFindCodeDto.java
  src/main/java/com/dku/council/domain/user/model/dto/request/RequestVerifyTokenCodeDto.java
  src/main/java/com/dku/council/domain/user/model/dto/response/ResponseChangeTokenDto.java
  src/main/java/com/dku/council/domain/user/model/entity/User.java
  src/main/java/com/dku/council/domain/user/repository/UserFindRepository.java
  src/main/java/com/dku/council/domain/user/repository/impl/UserFindRedisRepository.java
  src/main/java/com/dku/council/domain/user/service/UserFindService.java
  src/main/java/com/dku/council/domain/user/service/UserService.java
  src/main/resources/messages.properties
  src/test/java/com/dku/council/domain/user/repository/impl/UserFindRedisRepositoryTest.java
  src/test/java/com/dku/council/domain/user/service/UserFindServiceTest.java
  src/test/resources/messages.properties
Labels: feat

#189 유저 비밀번호 찾기 및 재설정 수정
  src/main/java/com/dku/council/domain/user/controller/UserController.java
  src/main/java/com/dku/council/domain/user/service/UserFindService.java
  src/main/java/com/dku/council/domain/user/service/UserService.java
  src/test/java/com/dku/council/domain/user/service/UserFindServiceTest.java
Labels: update

#186 좋아요 Redis cache clear안하는 버그
  .gitignore
  src/main/java/com/dku/council/domain/like/scheduler/PostLikeDumpScheduler.java
  src/main/java/com/dku/council/domain/like/service/PostLikeService.java
  src/main/java/com/dku/council/domain/like/service/impl/DBPostLikeServiceImpl.java
  src/main/java/com/dku/council/domain/like/service/impl/RedisPostLikeServiceImpl.java
  src/main/java/com/dku/council/domain/post/controller/GeneralForumController.java
  src/test/java/com/dku/council/domain/like/service/RedisPostLikeServiceImplTest.java
  src/test/java/com/dku/council/domain/post/service/GenericPostServiceTest.java
Labels: bug

#190 테스트 유틸리티 추가
  src/main/java/com/dku/council/debug/TestController.java
  src/main/java/com/dku/council/domain/like/service/impl/RedisPostLikeServiceImpl.java
  src/main/java/com/dku/council/domain/tag/model/entity/Tag.java
  src/main/java/com/dku/council/domain/user/service/UserFindService.java
  src/main/java/com/dku/council/domain/user/service/UserService.java
  src/main/resources/bustable/weekday/bearstatue/shuttle-bus.table
  src/main/resources/bustable/weekday/dkugate/shuttle-bus.table
  src/test/java/com/dku/council/domain/tag/repository/TagRepositoryTest.java
Labels: test

#193 내가쓴 글, 댓글단 글, 좋아요한 글 API
  src/main/java/com/dku/council/domain/comment/CommentRepository.java
  src/main/java/com/dku/council/domain/comment/model/dto/CommentedPostResponseDto.java
  src/main/java/com/dku/council/domain/like/repository/PostLikePersistenceRepository.java
  src/main/java/com/dku/council/domain/post/model/entity/Post.java
  src/main/java/com/dku/council/domain/post/repository/GenericPostRepository.java
  src/main/java/com/dku/council/domain/post/repository/PostRepository.java
  src/main/java/com/dku/council/domain/post/service/GenericPostService.java
  src/main/java/com/dku/council/domain/user/controller/UserController.java
  src/main/java/com/dku/council/domain/user/repository/MajorRepository.java
  src/main/java/com/dku/council/domain/user/service/MyCommentedPostService.java
  src/main/java/com/dku/council/domain/user/service/MyLikedPostService.java
  src/main/java/com/dku/council/domain/user/service/MyPostService.java
  src/main/java/com/dku/council/domain/user/service/UserService.java
Labels: feat

#203 내가 쓴 댓글 조회 API
  src/main/java/com/dku/council/domain/comment/CommentRepository.java
Labels: fix

#204 내가 쓴 댓글, Schedule 공통 ID 수정
  src/main/java/com/dku/council/domain/comment/CommentRepository.java
  src/main/java/com/dku/council/domain/comment/model/dto/CommentedPostResponseDto.java
  src/main/java/com/dku/council/domain/timetable/model/entity/TimeSchedule.java
  src/main/java/com/dku/council/domain/user/controller/UserController.java
  src/main/java/com/dku/council/domain/user/service/MyPostService.java
Labels: refactor

#208 Prefix 수정
  src/main/java/com/dku/council/domain/post/service/GenericPostService.java
Labels: refactor
