Repository EveryUniv/student-council-homepage-backend, pull requests merged in 2023-02, with the labels that each got.

#3 Feat : SecurityExceptionHandler & Fix : TOKEN HEADER -> Authorization
  src/main/java/com/dku/council/debug/TestController.java
  src/main/java/com/dku/council/global/auth/CustomAccessDeniedHandler.java
  src/main/java/com/dku/council/global/auth/CustomAuthenticationEntryPoint.java
  src/main/java/com/dku/council/global/auth/JwtAuthenticationFilter.java
  src/main/java/com/dku/council/global/auth/jwt/AuthenticationToken.java
  src/main/java/com/dku/council/global/auth/jwt/AuthenticationTokenProvider.java
  src/main/java/com/dku/council/global/auth/jwt/JwtAuthenticationToken.java
  src/main/java/com/dku/council/global/auth/jwt/JwtProvider.java
  src/main/java/com/dku/council/global/config/SecurityConfig.java
  src/main/java/com/dku/council/global/config/SwaggerConfig.java
  src/main/java/com/dku/council/global/exception/ErrorCode.java
  src/test/java/com/dku/council/global/auth/jwt/JwtAuthenticationTokenProviderTest.java
  src/test/java/com/dku/council/global/auth/jwt/JwtProviderTest.java
Labels: enhancement

#4 docs: 도메인 모델 및 규칙 추가
  README.md
  images/domain_model.png
  introdution.md
Labels: documentation

#5 Dev branch 업데이트
  README.md
  images/domain_model.png
  introdution.md
Labels: chore

#6 CI 및 Lombok 설정
  .github/workflows/ci.yml
  lombok.config
  src/main/java/com/dku/council/domain/UserRole.java
  src/main/java/com/dku/council/global/auth/CustomAccessDeniedHandler.java
  src/main/java/com/dku/council/global/auth/CustomAuthenticationEntryPoint.java
  src/main/java/com/dku/council/global/auth/JwtAuthenticationFilter.java
  src/main/java/com/dku/council/global/auth/jwt/JwtAuthentication.java
  src/main/java/com/dku/council/global/auth/jwt/JwtProvider.java
  src/main/java/com/dku/council/global/config/SecurityConfig.java
  src/main/java/com/dku/council/global/exception/ControllerAdvisor.java
  src/main/resources/application.default.yml
  src/main/resources/application.yml
  src/test/java/com/dku/council/DkuCouncilHomepageApplicationTests.java
Labels: chore

#10 Error Handling 방식 개선
  src/main/java/com/dku/council/debug/TestController.java
  src/main/java/com/dku/council/global/auth/CustomAccessDeniedHandler.java
  src/main/java/com/dku/council/global/auth/CustomAuthenticationEntryPoint.java
  src/main/java/com/dku/council/global/auth/JwtAuthenticationFilter.java
  src/main/java/com/dku/council/global/auth/jwt/JwtProvider.java
  src/main/java/com/dku/council/global/config/SecurityConfig.java
  src/main/java/com/dku/council/global/config/WebConfig.java
  src/main/java/com/dku/council/global/error/ControllerAdvisor.java
  src/main/java/com/dku/council/global/error/ErrorResponseDto.java
  src/main/java/com/dku/council/global/error/ExceptionHandlerFilter.java
  src/main/java/com/dku/council/global/error/exception/AccessTokenRequiredException.java
  src/main/java/com/dku/council/global/error/exception/ExpiredTokenException.java
  src/main/java/com/dku/council/global/error/exception/IllegalTypeException.java
  src/main/java/com/dku/council/global/error/exception/InvalidTokenException.java
  src/main/java/com/dku/council/global/error/exception/LocalizedMessageException.java
  src/main/java/com/dku/council/global/error/exception/NotGrantedException.java
  src/main/java/com/dku/council/global/exception/ControllerAdvisor.java
  src/main/java/com/dku/council/global/exception/CustomException.java
  src/main/java/com/dku/council/global/exception/ErrorCode.java
  src/main/java/com/dku/council/global/exception/ExceptionDto.java
  src/main/java/com/dku/council/global/interceptor/SuccessResponseDto.java
  src/main/java/com/dku/council/global/interceptor/SuccessResponseInterceptor.java
  src/main/resources/application.default.yml
  src/main/resources/application.yml
  src/main/resources/errors.properties
  src/test/java/com/dku/council/global/error/ErrorResponseDtoTest.java
Labels: feat

#11 일부 rule 개정
  README.md
  images/domain_model.png
  images/erd.png
  introdution.md
  rules.md
Labels: docs

#12 User model 도입
  .gitignore
  src/main/java/com/dku/council/DkuCouncilHomepageApplication.java
  src/main/java/com/dku/council/debug/TestController.java
  src/main/java/com/dku/council/domain/user/Department.java
  src/main/java/com/dku/council/domain/user/Major.java
  src/main/java/com/dku/council/domain/user/User.java
  src/main/java/com/dku/council/domain/user/UserStatus.java
  src/main/java/com/dku/council/global/base/BaseEntity.java
  src/main/resources/application.default.yml
  src/main/resources/application.yml
  src/main/resources/majors.properties
  src/test/java/com/dku/council/domain/user/DepartmentTest.java
  src/test/java/com/dku/council/domain/user/MajorTest.java
  src/test/java/com/dku/council/global/auth/jwt/JwtProviderTest.java
Labels: feat

#13 Error Handling 개선 및 Controller 조건부 활성화 추가
  build.gradle
  src/main/java/com/dku/council/debug/TestController.java
  src/main/java/com/dku/council/debug/TestDto.java
  src/main/java/com/dku/council/global/error/ControllerAdvisor.java
  src/main/java/com/dku/council/global/error/ErrorResponseDto.java
  src/main/java/com/dku/council/global/error/ExceptionHandlerFilter.java
  src/main/java/com/dku/council/global/error/exception/BadRequestException.java
  src/main/java/com/dku/council/global/error/exception/BindingFailedException.java
  src/main/java/com/dku/council/global/error/exception/LocalizedMessageException.java
  src/main/resources/errors.properties
  src/test/java/com/dku/council/global/error/ErrorResponseDtoTest.java
Labels: feat

#14 Release 0.1.0
  .github/workflows/ci.yml
  .gitignore
  README.md
  build.gradle
  images/domain_model.png
  images/erd.png
  introdution.md
  rules.md
  src/main/java/com/dku/council/DkuCouncilHomepageApplication.java
  src/main/java/com/dku/council/debug/TestController.java
  src/main/java/com/dku/council/debug/TestDto.java
  src/main/java/com/dku/council/domain/user/Department.java
  src/main/java/com/dku/council/domain/user/Major.java
  src/main/java/com/dku/council/domain/user/User.java
  src/main/java/com/dku/council/domain/user/UserStatus.java
  src/main/java/com/dku/council/global/auth/CustomAccessDeniedHandler.java
  src/main/java/com/dku/council/global/auth/CustomAuthenticationEntryPoint.java
  src/main/java/com/dku/council/global/auth/JwtAuthenticationFilter.java
  src/main/java/com/dku/council/global/auth/jwt/JwtProvider.java
  src/main/java/com/dku/council/global/base/BaseEntity.java
  src/main/java/com/dku/council/global/config/SecurityConfig.java
  src/main/java/com/dku/council/global/config/WebConfig.java
  src/main/java/com/dku/council/global/error/ControllerAdvisor.java
  src/main/java/com/dku/council/global/error/ErrorResponseDto.java
  src/main/java/com/dku/council/global/error/ExceptionHandlerFilter.java
  src/main/java/com/dku/council/global/error/exception/AccessTokenRequiredException.java
  src/main/java/com/dku/council/global/error/exception/BadRequestException.java
  src/main/java/com/dku/council/global/error/exception/BindingFailedException.java
  src/main/java/com/dku/council/global/error/exception/ExpiredTokenException.java
  src/main/java/com/dku/council/global/error/exception/IllegalTypeException.java
  src/main/java/com/dku/council/global/error/exception/InvalidTokenException.java
  src/main/java/com/dku/council/global/error/exception/LocalizedMessageException.java
  src/main/java/com/dku/council/global/error/exception/NotGrantedException.java
  src/main/java/com/dku/council/global/exception/ControllerAdvisor.java
  src/main/java/com/dku/council/global/exception/CustomException.java
  src/main/java/com/dku/council/global/exception/ErrorCode.java
  src/main/java/com/dku/council/global/exception/ExceptionDto.java
  src/main/java/com/dku/council/global/interceptor/SuccessResponseDto.java
  src/main/java/com/dku/council/global/interceptor/SuccessResponseInterceptor.java
  src/main/resources/application.default.yml
  src/main/resources/application.yml
  src/main/resources/errors.properties
  src/main/resources/majors.properties
  src/test/java/com/dku/council/domain/user/DepartmentTest.java
  src/test/java/com/dku/council/domain/user/MajorTest.java
  src/test/java/com/dku/council/global/auth/jwt/JwtProviderTest.java
  src/test/java/com/dku/council/global/error/ErrorResponseDtoTest.java
Labels: release

#15 Rule 최신화
  CODEOWNERS
  images/erd.png
  rules.md
Labels: docs

#17 단대 크롤러 추가
  build.gradle
  lombok.config
  src/main/java/com/dku/council/domain/user/model/Major.java
  src/main/java/com/dku/council/global/config/WebConfig.java
  src/main/java/com/dku/council/global/config/qualifier/ChromeAgentWebClient.java
  src/main/java/com/dku/council/global/error/exception/MajorNotFoundException.java
  src/main/java/com/dku/council/infra/dku/exception/DkuFailedCrawlingException.java
  src/main/java/com/dku/council/infra/dku/exception/DkuFailedLoginException.java
  src/main/java/com/dku/council/infra/dku/model/DkuAuth.java
  src/main/java/com/dku/council/infra/dku/model/StudentInfo.java
  src/main/java/com/dku/council/infra/dku/service/DkuAuthenticationService.java
  src/main/java/com/dku/council/infra/dku/service/DkuCrawlerService.java
  src/main/resources/errors.properties
  src/test/java/com/dku/council/domain/user/MajorTest.java
  src/test/java/com/dku/council/infra/dku/service/DkuAuthenticationServiceTest.java
  src/test/java/com/dku/council/infra/dku/service/DkuCrawlerServiceTest.java
  src/test/java/com/dku/council/infra/nhn/service/NHNAuthServiceTest.java
  src/test/java/com/dku/council/infra/nhn/service/SMSServiceTest.java
  src/test/java/com/dku/council/util/MockServerUtil.java
  src/test/java/com/dku/council/util/WebClientUtil.java
  src/test/resources/mockdata/dku/login-response.html
  src/test/resources/mockdata/dku/student-info-response-failed-1.html
  src/test/resources/mockdata/dku/student-info-response-failed-2.html
  src/test/resources/mockdata/dku/student-info-response.html
Labels: feat

#18 좋아요 기능 추가
  .github/workflows/ci.yml
  build.gradle
  src/main/java/com/dku/council/domain/like/PostLikeDumpTask.java
  src/main/java/com/dku/council/domain/like/PostLikeService.java
  src/main/java/com/dku/council/domain/like/model/LikeEntry.java
  src/main/java/com/dku/council/domain/like/model/LikeState.java
  src/main/java/com/dku/council/domain/like/repository/PostLikeMemoryRepository.java
  src/main/java/com/dku/council/domain/like/repository/PostLikePersistenceRepository.java
  src/main/java/com/dku/council/domain/like/repository/impl/PostLikeRedisRepository.java
  src/main/java/com/dku/council/domain/post/model/entity/Post.java
  src/main/java/com/dku/council/domain/post/repository/PostRepository.java
  src/main/java/com/dku/council/domain/post/service/NewsService.java
  src/main/java/com/dku/council/domain/user/model/Major.java
  src/main/java/com/dku/council/global/config/QuartzConfig.java
  src/main/java/com/dku/council/global/config/RedisConfig.java
  src/main/java/com/dku/council/infra/dku/exception/DkuFailedCrawlingException.java
  src/main/java/com/dku/council/infra/dku/service/DkuCrawlerService.java
  src/main/java/com/dku/council/infra/nhn/model/dto/response/ResponseToken.java
  src/main/java/com/dku/council/infra/nhn/service/impl/NHNAuthServiceImpl.java
  src/test/java/com/dku/council/config/EmbeddedRedisConfig.java
  src/test/java/com/dku/council/domain/like/PostLikeServiceTest.java
  src/test/java/com/dku/council/domain/like/repository/impl/PostLikeRedisRepositoryTest.java
  src/test/java/com/dku/council/global/config/RedisConnectionTest.java
  src/test/java/com/dku/council/util/MockServerUtil.java
  src/test/java/com/dku/council/util/PropertiesBase64Encoder.java
Labels: feat

#20 조회수 기능 구현
  build.gradle
  src/main/java/com/dku/council/domain/like/repository/impl/PostLikeRedisRepository.java
  src/main/java/com/dku/council/domain/post/model/entity/Post.java
  src/main/java/com/dku/council/domain/post/repository/PostRepository.java
  src/main/java/com/dku/council/domain/post/repository/ViewCountMemoryRepository.java
  src/main/java/com/dku/council/domain/post/repository/impl/ViewCountRedisRepository.java
  src/main/java/com/dku/council/domain/post/service/NewsService.java
  src/main/java/com/dku/council/domain/post/service/PostService.java
  src/main/java/com/dku/council/domain/post/service/ViewCountService.java
  src/main/java/com/dku/council/global/config/RedisConfig.java
  src/main/java/com/dku/council/global/config/WebConfig.java
  src/test/java/com/dku/council/config/EmbeddedRedisConfig.java
  src/test/java/com/dku/council/domain/post/repository/impl/ViewCountRedisRepositoryTest.java
  src/test/java/com/dku/council/domain/post/service/NewsServiceTest.java
  src/test/java/com/dku/council/domain/post/service/ViewCountServiceTest.java
Labels: feat

#22 자유게시판 CRUD 및 테스트 코드 작성
  src/main/java/com/dku/council/domain/category/repository/CategoryRepository.java
  src/main/java/com/dku/council/domain/comment/controller/CommentController.java
  src/main/java/com/dku/council/domain/comment/model/dto/CommentDto.java
  src/main/java/com/dku/council/domain/comment/model/dto/request/RequestCreateCommentDto.java
  src/main/java/com/dku/council/domain/comment/model/entity/Comment.java
  src/main/java/com/dku/council/domain/comment/model/entity/CommentLog.java
  src/main/java/com/dku/council/domain/comment/service/CommentService.java
  src/main/java/com/dku/council/domain/post/controller/GeneralForumController.java
  src/main/java/com/dku/council/domain/post/exception/CategoryNotFoundException.java
  src/main/java/com/dku/council/domain/post/model/dto/page/SummarizedGeneralForumDto.java
  src/main/java/com/dku/council/domain/post/model/dto/request/RequestCreateGeneralForumDto.java
  src/main/java/com/dku/council/domain/post/model/dto/response/ResponseSingleGeneralForumDto.java
  src/main/java/com/dku/council/domain/post/model/dto/response/ResponseSingleNewsDto.java
  src/main/java/com/dku/council/domain/post/model/entity/Post.java
  src/main/java/com/dku/council/domain/post/repository/GeneralForumRepository.java
  src/main/java/com/dku/council/domain/post/repository/spec/PostSpec.java
  src/main/java/com/dku/council/domain/post/service/GeneralForumService.java
  src/main/resources/errors.properties
  src/test/java/com/dku/council/domain/post/service/GeneralForumTest.java
Labels: feat

#21 회원가입, 단대 학생인증 구현
  src/main/java/com/dku/council/debug/TestController.java
  src/main/java/com/dku/council/domain/like/PostLikeDumpTask.java
  src/main/java/com/dku/council/domain/like/PostLikeService.java
  src/main/java/com/dku/council/domain/like/model/LikeState.java
  src/main/java/com/dku/council/domain/like/repository/impl/PostLikeRedisRepository.java
  src/main/java/com/dku/council/domain/post/controller/NewsController.java
  src/main/java/com/dku/council/domain/post/repository/impl/ViewCountRedisRepository.java
  src/main/java/com/dku/council/domain/post/service/ViewCountService.java
  src/main/java/com/dku/council/domain/user/controller/DKUController.java
  src/main/java/com/dku/council/domain/user/controller/SMSController.java
  src/main/java/com/dku/council/domain/user/controller/UserController.java
  src/main/java/com/dku/council/domain/user/exception/NotDKUAuthorizedException.java
  src/main/java/com/dku/council/domain/user/exception/NotSMSAuthorizedException.java
  src/main/java/com/dku/council/domain/user/exception/NotSMSSentException.java
  src/main/java/com/dku/council/domain/user/exception/WrongSMSCodeException.java
  src/main/java/com/dku/council/domain/user/model/Department.java
  src/main/java/com/dku/council/domain/user/model/Major.java
  src/main/java/com/dku/council/domain/user/model/SMSAuthObject.java
  src/main/java/com/dku/council/domain/user/model/UserStatus.java
  src/main/java/com/dku/council/domain/user/model/dto/request/RequestSendSMSCodeDto.java
  src/main/java/com/dku/council/domain/user/model/dto/request/RequestSignupDto.java
  src/main/java/com/dku/council/domain/user/model/dto/request/RequestVerifySMSCodeDto.java
  src/main/java/com/dku/council/domain/user/model/dto/request/RequestVerifyStudentDto.java
  src/main/java/com/dku/council/domain/user/model/dto/response/ResponseStudentInfoDto.java
  src/main/java/com/dku/council/domain/user/model/dto/response/ResponseVerifyStudentDto.java
  src/main/java/com/dku/council/domain/user/model/entity/User.java
  src/main/java/com/dku/council/domain/user/repository/SignupAuthRepository.java
  src/main/java/com/dku/council/domain/user/repository/impl/SignupAuthRedisRepository.java
  src/main/java/com/dku/council/domain/user/service/DKUAuthService.java
  src/main/java/com/dku/council/domain/user/service/SMSVerificationService.java
  src/main/java/com/dku/council/domain/user/service/UserService.java
  src/main/java/com/dku/council/global/auth/jwt/JwtProvider.java
  src/main/java/com/dku/council/global/config/RedisConfig.java
  src/main/java/com/dku/council/global/config/RedisKeys.java
  src/main/java/com/dku/council/global/error/exception/MajorNotFoundException.java
  src/main/java/com/dku/council/global/interceptor/VoidSuccessResponseInterceptor.java
  src/main/java/com/dku/council/infra/dku/model/StudentInfo.java
  src/main/java/com/dku/council/infra/dku/service/DkuAuthenticationService.java
  src/main/java/com/dku/council/infra/dku/service/DkuCrawlerService.java
  src/main/resources/errors.properties
  src/main/resources/majors.properties
  src/main/resources/messages.properties
  src/test/java/com/dku/council/domain/like/PostLikeServiceTest.java
  src/test/java/com/dku/council/domain/like/repository/impl/PostLikeRedisRepositoryTest.java
  src/test/java/com/dku/council/domain/post/repository/impl/ViewCountRedisRepositoryTest.java
  src/test/java/com/dku/council/domain/post/service/NewsServiceTest.java
  src/test/java/com/dku/council/domain/user/MajorTest.java
  src/test/java/com/dku/council/global/auth/jwt/JwtProviderTest.java
  src/test/java/com/dku/council/infra/dku/service/DkuCrawlerServiceTest.java
Labels: feat

#25 Conference 구현
  src/main/java/com/dku/council/domain/post/controller/ConferenceController.java
  src/main/java/com/dku/council/domain/post/model/dto/page/SummarizedConferenceDto.java
  src/main/java/com/dku/council/domain/post/model/dto/page/SummarizedRuleDto.java
  src/main/java/com/dku/council/domain/post/model/dto/request/RequestCreateConferenceDto.java
  src/main/java/com/dku/council/domain/post/model/dto/request/RequestCreateGeneralForumDto.java
  src/main/java/com/dku/council/domain/post/model/dto/response/ResponseSingleGeneralForumDto.java
  src/main/java/com/dku/council/domain/post/model/dto/response/ResponseSingleRuleDto.java
  src/main/java/com/dku/council/domain/post/model/entity/posttype/Conference.java
  src/main/java/com/dku/council/domain/post/repository/ConferenceRepository.java
  src/main/java/com/dku/council/domain/post/service/ConferenceService.java
  src/main/java/com/dku/council/domain/post/service/GeneralForumService.java
  src/main/java/com/dku/council/domain/post/service/RuleService.java
Labels: feat

#28 테스트 수정
  src/main/java/com/dku/council/domain/comment/service/impl/CommentServiceImpl.java
  src/test/java/com/dku/council/domain/post/service/GeneralForumTest.java
  src/test/java/com/dku/council/domain/post/service/NewsServiceTest.java
Labels: bug

#29 CD 테스트
  src/main/java/com/dku/council/domain/comment/service/impl/CommentServiceImpl.java
  src/test/java/com/dku/council/domain/post/service/GeneralForumTest.java
  src/test/java/com/dku/council/domain/post/service/NewsServiceTest.java
Labels: chore

#33 Redis password 추가
  src/main/java/com/dku/council/global/config/RedisConfig.java
Labels: bug

#35 HealthController 추가
  src/main/java/com/dku/council/domain/health/HealthController.java
Labels: feat

#37 Dev
  .github/workflows/dev_cd.yml
  .github/workflows/prod_cd.yml
Labels: deploy

#38 dev cd network 설정
  .github/workflows/dev_cd.yml
Labels: deploy

#41 개발 서버에 배포
  .github/workflows/prod_cd.yml
  src/main/java/com/dku/council/debug/TestController.java
  src/main/java/com/dku/council/domain/comment/controller/CommentController.java
  src/main/java/com/dku/council/domain/post/controller/ConferenceController.java
  src/main/java/com/dku/council/domain/post/controller/GeneralForumController.java
  src/main/java/com/dku/council/domain/post/controller/NewsController.java
  src/main/java/com/dku/council/domain/post/controller/RuleController.java
  src/main/java/com/dku/council/domain/post/model/PostStatus.java
  src/main/java/com/dku/council/domain/post/model/dto/page/SummarizedConferenceDto.java
  src/main/java/com/dku/council/domain/post/model/dto/page/SummarizedGeneralForumDto.java
  src/main/java/com/dku/council/domain/post/model/dto/page/SummarizedGenericPostDto.java
  src/main/java/com/dku/council/domain/post/model/dto/page/SummarizedRuleDto.java
  src/main/java/com/dku/council/domain/post/model/dto/request/RequestCreateConferenceDto.java
  src/main/java/com/dku/council/domain/post/model/dto/request/RequestCreateGeneralForumDto.java
  src/main/java/com/dku/council/domain/post/model/dto/request/RequestCreateGenericPostDto.java
  src/main/java/com/dku/council/domain/post/model/dto/request/RequestCreateNewsDto.java
  src/main/java/com/dku/council/domain/post/model/dto/request/RequestCreatePostDto.java
  src/main/java/com/dku/council/domain/post/model/dto/request/RequestCreateRuleDto.java
  src/main/java/com/dku/council/domain/post/model/dto/response/ResponseSingleGeneralForumDto.java
  src/main/java/com/dku/council/domain/post/model/dto/response/ResponseSingleGenericPostDto.java
  src/main/java/com/dku/council/domain/post/model/dto/response/ResponseSingleNewsDto.java
  src/main/java/com/dku/council/domain/post/model/dto/response/ResponseSingleRuleDto.java
  src/main/java/com/dku/council/domain/post/repository/ConferenceRepository.java
  src/main/java/com/dku/council/domain/post/repository/GeneralForumRepository.java
  src/main/java/com/dku/council/domain/post/repository/GenericPostRepository.java
  src/main/java/com/dku/council/domain/post/repository/NewsRepository.java
  src/main/java/com/dku/council/domain/post/repository/RuleRepository.java
  src/main/java/com/dku/council/domain/post/repository/spec/PostSpec.java
  src/main/java/com/dku/council/domain/post/service/ConferenceService.java
  src/main/java/com/dku/council/domain/post/service/GeneralForumService.java
  src/main/java/com/dku/council/domain/post/service/GenericPostService.java
  src/main/java/com/dku/council/domain/post/service/NewsService.java
  src/main/java/com/dku/council/domain/post/service/RuleService.java
  src/main/java/com/dku/council/domain/user/controller/UserController.java
  src/main/java/com/dku/council/global/auth/jwt/AppAuthentication.java
  src/main/java/com/dku/council/global/auth/jwt/JwtAuthentication.java
  src/main/java/com/dku/council/global/auth/jwt/JwtProvider.java
  src/main/java/com/dku/council/global/config/SecurityConfig.java
  src/main/java/com/dku/council/global/error/ControllerAdvisor.java
  src/main/java/com/dku/council/global/error/exception/NotGrantedException.java
  src/test/java/com/dku/council/common/IntegrationControllerTest.java
  src/test/java/com/dku/council/config/EmbeddedRedisConfig.java
  src/test/java/com/dku/council/domain/like/PostLikeServiceTest.java
  src/test/java/com/dku/council/domain/post/controller/NewsControllerTest.java
  src/test/java/com/dku/council/domain/post/service/GeneralForumTest.java
  src/test/java/com/dku/council/domain/post/service/GenericPostServiceTest.java
  src/test/java/com/dku/council/domain/post/service/NewsServiceTest.java
  src/test/java/com/dku/council/global/auth/jwt/JwtProviderTest.java
  src/test/java/com/dku/council/infra/nhn/service/FileUploadServiceTest.java
  src/test/java/com/dku/council/mock/DummyMultipartFile.java
  src/test/java/com/dku/council/mock/MultipartFileMock.java
  src/test/java/com/dku/council/mock/NewsMock.java
  src/test/java/com/dku/council/mock/UploadedFileMock.java
  src/test/java/com/dku/council/mock/UserMock.java
  src/test/java/com/dku/council/util/FieldInjector.java
Labels: deploy

#42 개발 서버에 재배포
  src/test/java/com/dku/council/domain/post/controller/NewsControllerTest.java
Labels: deploy

#44 개발 서버에 배포
  build.gradle
  src/main/java/com/dku/council/debug/TestController.java
  src/main/java/com/dku/council/domain/category/service/CategoryService.java
  src/main/java/com/dku/council/domain/comment/controller/CommentController.java
  src/main/java/com/dku/council/domain/comment/service/CommentService.java
  src/main/java/com/dku/council/domain/comment/service/impl/CommentServiceImpl.java
  src/main/java/com/dku/council/domain/health/HealthController.java
  src/main/java/com/dku/council/domain/like/repository/impl/PostLikeRedisRepository.java
  src/main/java/com/dku/council/domain/post/controller/ConferenceController.java
  src/main/java/com/dku/council/domain/post/controller/GeneralForumController.java
  src/main/java/com/dku/council/domain/post/controller/NewsController.java
  src/main/java/com/dku/council/domain/post/controller/RuleController.java
  src/main/java/com/dku/council/domain/post/model/dto/page/SummarizedGenericPostDto.java
  src/main/java/com/dku/council/domain/post/model/dto/request/RequestCreateConferenceDto.java
  src/main/java/com/dku/council/domain/post/model/dto/request/RequestCreateGeneralForumDto.java
  src/main/java/com/dku/council/domain/post/model/dto/request/RequestCreateGenericPostDto.java
  src/main/java/com/dku/council/domain/post/model/dto/request/RequestCreateNewsDto.java
  src/main/java/com/dku/council/domain/post/model/dto/request/RequestCreateRuleDto.java
  src/main/java/com/dku/council/domain/post/model/dto/response/ResponseSingleGenericPostDto.java
  src/main/java/com/dku/council/domain/post/repository/impl/ViewCountRedisRepository.java
  src/main/java/com/dku/council/domain/post/service/GenericPostService.java
  src/main/java/com/dku/council/domain/user/model/dto/response/ResponseLoginDto.java
  src/main/java/com/dku/council/domain/user/model/entity/User.java
  src/main/java/com/dku/council/domain/user/repository/impl/SignupAuthRedisRepository.java
  src/main/java/com/dku/council/domain/user/service/UserService.java
  src/main/java/com/dku/council/global/auth/jwt/JwtProvider.java
  src/main/java/com/dku/council/global/auth/role/AdminOnly.java
  src/main/java/com/dku/council/global/auth/role/UserOnly.java
  src/main/java/com/dku/council/global/auth/role/UserRole.java
  src/main/java/com/dku/council/global/auth/role/UserRoleNames.java
  src/main/java/com/dku/council/global/config/SecurityConfig.java
  src/main/java/com/dku/council/global/config/redis/RedisConfig.java
  src/main/java/com/dku/council/global/config/redis/RedisKeys.java
  src/main/java/com/dku/council/global/config/swagger/JavadocPropertyCustomizer.java
  src/main/java/com/dku/council/global/config/swagger/SpringDocJavadocProvider.java
  src/main/java/com/dku/council/global/config/swagger/SwaggerConfig.java
  src/test/java/com/dku/council/common/AbstractContainerRedisTest.java
  src/test/java/com/dku/council/common/DevTest.java
  src/test/java/com/dku/council/common/IntegrationControllerTest.java
  src/test/java/com/dku/council/config/EmbeddedRedisConfig.java
  src/test/java/com/dku/council/domain/like/repository/impl/PostLikeRedisRepositoryTest.java
  src/test/java/com/dku/council/domain/post/controller/NewsControllerTest.java
  src/test/java/com/dku/council/domain/post/repository/impl/ViewCountRedisRepositoryTest.java
  src/test/java/com/dku/council/domain/post/service/GenericPostServiceTest.java
  src/test/java/com/dku/council/mock/NewsMock.java
  src/test/java/com/dku/council/mock/UserMock.java
  src/test/resources/errors.properties
  src/test/resources/majors.properties
  src/test/resources/messages.properties
Labels: deploy

#46 개발 서버에 배포
  src/main/java/com/dku/council/domain/post/model/dto/response/ResponsePostIdDto.java
  src/main/java/com/dku/council/global/auth/jwt/AppAuthentication.java
  src/main/java/com/dku/council/global/auth/jwt/JwtAuthentication.java
  src/main/java/com/dku/council/global/auth/jwt/JwtProvider.java
  src/main/java/com/dku/council/global/auth/role/AdminOnly.java
  src/main/java/com/dku/council/global/auth/role/UserAuthNames.java
  src/main/java/com/dku/council/global/auth/role/UserOnly.java
  src/main/java/com/dku/council/global/auth/role/UserRole.java
  src/main/java/com/dku/council/global/config/swagger/SwaggerConfig.java
  src/test/java/com/dku/council/common/MvcMockResponse.java
  src/test/java/com/dku/council/common/OnlyDevTest.java
  src/test/java/com/dku/council/domain/like/repository/impl/PostLikeRedisRepositoryTest.java
  src/test/java/com/dku/council/domain/post/controller/NewsControllerTest.java
  src/test/java/com/dku/council/domain/post/repository/impl/ViewCountRedisRepositoryTest.java
  src/test/java/com/dku/council/infra/dku/service/DkuCrawlerServiceTest.java
  src/test/java/com/dku/council/infra/nhn/service/NHNAuthServiceTest.java
  src/test/java/com/dku/council/infra/nhn/service/ObjectStorageServiceTest.java
  src/test/java/com/dku/council/infra/nhn/service/SMSServiceTest.java
  src/test/java/com/dku/council/mock/NewsMock.java
  src/test/java/com/dku/council/mock/RandomGen.java
  src/test/java/com/dku/council/mock/ServerMock.java
  src/test/java/com/dku/council/mock/UserMock.java
  src/test/java/com/dku/council/mock/user/UserAuth.java
  src/test/java/com/dku/council/mock/user/WithMockAppUser.java
  src/test/java/com/dku/council/mock/user/WithMockAppUserSecurityContextFactory.java
  src/test/java/com/dku/council/util/PropertiesBase64Encoder.java
Labels: deploy

#47 Swagger url 수정
  src/main/java/com/dku/council/domain/post/controller/RuleController.java
  src/main/java/com/dku/council/global/config/swagger/SwaggerConfig.java
Labels: bug

#48 개발 서버에 배포
  src/main/java/com/dku/council/domain/post/controller/RuleController.java
  src/main/java/com/dku/council/global/config/swagger/SwaggerConfig.java
Labels: deploy

#49 Post Generic 분해
  src/main/java/com/dku/council/domain/post/controller/ConferenceController.java
  src/main/java/com/dku/council/domain/post/controller/GeneralForumController.java
  src/main/java/com/dku/council/domain/post/controller/NewsController.java
  src/main/java/com/dku/council/domain/post/controller/RuleController.java
  src/main/java/com/dku/council/domain/post/model/dto/request/RequestCreateConferenceDto.java
  src/main/java/com/dku/council/domain/post/repository/ConferenceRepository.java
  src/main/java/com/dku/council/domain/post/repository/GeneralForumRepository.java
  src/main/java/com/dku/council/domain/post/repository/GenericPostRepository.java
  src/main/java/com/dku/council/domain/post/repository/NewsRepository.java
  src/main/java/com/dku/council/domain/post/repository/RuleRepository.java
  src/main/java/com/dku/council/domain/post/service/ConferenceService.java
  src/main/java/com/dku/council/domain/post/service/GeneralForumService.java
  src/main/java/com/dku/council/domain/post/service/GenericPostService.java
  src/main/java/com/dku/council/domain/post/service/NewsService.java
  src/main/java/com/dku/council/domain/post/service/RuleService.java
  src/test/java/com/dku/council/domain/post/service/GenericPostServiceTest.java
Labels: bug

#50 개발 서버에 배포
  src/main/java/com/dku/council/domain/post/controller/ConferenceController.java
  src/main/java/com/dku/council/domain/post/controller/GeneralForumController.java
  src/main/java/com/dku/council/domain/post/controller/NewsController.java
  src/main/java/com/dku/council/domain/post/controller/RuleController.java
  src/main/java/com/dku/council/domain/post/model/dto/request/RequestCreateConferenceDto.java
  src/main/java/com/dku/council/domain/post/repository/ConferenceRepository.java
  src/main/java/com/dku/council/domain/post/repository/GeneralForumRepository.java
  src/main/java/com/dku/council/domain/post/repository/GenericPostRepository.java
  src/main/java/com/dku/council/domain/post/repository/NewsRepository.java
  src/main/java/com/dku/council/domain/post/repository/RuleRepository.java
  src/main/java/com/dku/council/domain/post/service/ConferenceService.java
  src/main/java/com/dku/council/domain/post/service/GeneralForumService.java
  src/main/java/com/dku/council/domain/post/service/GenericPostService.java
  src/main/java/com/dku/council/domain/post/service/NewsService.java
  src/main/java/com/dku/council/domain/post/service/RuleService.java
  src/test/java/com/dku/council/domain/post/service/GenericPostServiceTest.java
Labels: deploy

#51 카테고리 및 댓글 구현
  README.md
  docs/README.md
  docs/images/domain_model.png
  docs/images/erd.png
  docs/rules.md
  src/main/java/com/dku/council/domain/category/controller/CategoryController.java
  src/main/java/com/dku/council/domain/category/exception/CategoryIntegrityException.java
  src/main/java/com/dku/council/domain/category/exception/CategoryNotFoundException.java
  src/main/java/com/dku/council/domain/category/model/dto/CategoryDto.java
  src/main/java/com/dku/council/domain/category/model/dto/RequestCreateCategoryDto.java
  src/main/java/com/dku/council/domain/category/model/dto/RequestRenameCategoryDto.java
  src/main/java/com/dku/council/domain/category/model/entity/Category.java
  src/main/java/com/dku/council/domain/category/repository/CategoryRepository.java
  src/main/java/com/dku/council/domain/category/service/CategoryService.java
  src/main/java/com/dku/council/domain/comment/CommentRepository.java
  src/main/java/com/dku/council/domain/comment/CommentStatus.java
  src/main/java/com/dku/council/domain/comment/controller/CommentController.java
  src/main/java/com/dku/council/domain/comment/exception/CommentNotFoundException.java
  src/main/java/com/dku/council/domain/comment/model/dto/CommentDto.java
  src/main/java/com/dku/council/domain/comment/model/dto/RequestCreateCommentDto.java
  src/main/java/com/dku/council/domain/comment/model/entity/Comment.java
  src/main/java/com/dku/council/domain/comment/service/CommentService.java
  src/main/java/com/dku/council/domain/post/controller/ConferenceController.java
  src/main/java/com/dku/council/domain/post/controller/GeneralForumController.java
  src/main/java/com/dku/council/domain/post/controller/NewsController.java
  src/main/java/com/dku/council/domain/post/controller/RuleController.java
  src/main/java/com/dku/council/domain/post/model/dto/request/RequestCreateConferenceDto.java
  src/main/java/com/dku/council/domain/post/model/dto/request/RequestCreateGeneralForumDto.java
  src/main/java/com/dku/council/domain/post/model/dto/request/RequestCreateGenericPostDto.java
  src/main/java/com/dku/council/domain/post/model/dto/request/RequestCreateNewsDto.java
  src/main/java/com/dku/council/domain/post/model/dto/request/RequestCreateRuleDto.java
  src/main/java/com/dku/council/domain/post/model/dto/response/ResponseSingleGenericPostDto.java
  src/main/java/com/dku/council/domain/post/model/entity/Post.java
  src/main/java/com/dku/council/domain/post/model/entity/posttype/Conference.java
  src/main/java/com/dku/council/domain/post/model/entity/posttype/GeneralForum.java
  src/main/java/com/dku/council/domain/post/model/entity/posttype/News.java
  src/main/java/com/dku/council/domain/post/model/entity/posttype/Petition.java
  src/main/java/com/dku/council/domain/post/model/entity/posttype/Rule.java
  src/main/java/com/dku/council/domain/post/service/GenericPostService.java
  src/main/java/com/dku/council/global/dto/ResponseIdDto.java
  src/main/java/com/dku/council/global/dto/ResponseSuccessDto.java
  src/main/java/com/dku/council/global/interceptor/VoidSuccessResponseInterceptor.java
  src/main/resources/errors.properties
  src/test/java/com/dku/council/domain/category/service/CategoryServiceTest.java
  src/test/java/com/dku/council/domain/comment/service/CommentServiceTest.java
  src/test/java/com/dku/council/domain/post/controller/NewsControllerTest.java
  src/test/java/com/dku/council/domain/post/service/GenericPostServiceTest.java
  src/test/java/com/dku/council/global/interceptor/VoidSuccessResponseInterceptorTest.java
  src/test/java/com/dku/council/mock/CategoryMock.java
  src/test/java/com/dku/council/mock/CommentMock.java
  src/test/java/com/dku/council/mock/RandomGen.java
  src/test/resources/errors.properties
Labels: feat

#52 개발 서버에 배포
  README.md
  docs/README.md
  docs/images/domain_model.png
  docs/images/erd.png
  docs/rules.md
  src/main/java/com/dku/council/domain/category/controller/CategoryController.java
  src/main/java/com/dku/council/domain/category/exception/CategoryIntegrityException.java
  src/main/java/com/dku/council/domain/category/exception/CategoryNotFoundException.java
  src/main/java/com/dku/council/domain/category/model/dto/CategoryDto.java
  src/main/java/com/dku/council/domain/category/model/dto/RequestCreateCategoryDto.java
  src/main/java/com/dku/council/domain/category/model/dto/RequestRenameCategoryDto.java
  src/main/java/com/dku/council/domain/category/model/entity/Category.java
  src/main/java/com/dku/council/domain/category/repository/CategoryRepository.java
  src/main/java/com/dku/council/domain/category/service/CategoryService.java
  src/main/java/com/dku/council/domain/comment/CommentRepository.java
  src/main/java/com/dku/council/domain/comment/CommentStatus.java
  src/main/java/com/dku/council/domain/comment/controller/CommentController.java
  src/main/java/com/dku/council/domain/comment/exception/CommentNotFoundException.java
  src/main/java/com/dku/council/domain/comment/model/dto/CommentDto.java
  src/main/java/com/dku/council/domain/comment/model/dto/RequestCreateCommentDto.java
  src/main/java/com/dku/council/domain/comment/model/entity/Comment.java
  src/main/java/com/dku/council/domain/comment/service/CommentService.java
  src/main/java/com/dku/council/domain/post/controller/ConferenceController.java
  src/main/java/com/dku/council/domain/post/controller/GeneralForumController.java
  src/main/java/com/dku/council/domain/post/controller/NewsController.java
  src/main/java/com/dku/council/domain/post/controller/RuleController.java
  src/main/java/com/dku/council/domain/post/model/dto/request/RequestCreateConferenceDto.java
  src/main/java/com/dku/council/domain/post/model/dto/request/RequestCreateGeneralForumDto.java
  src/main/java/com/dku/council/domain/post/model/dto/request/RequestCreateGenericPostDto.java
  src/main/java/com/dku/council/domain/post/model/dto/request/RequestCreateNewsDto.java
  src/main/java/com/dku/council/domain/post/model/dto/request/RequestCreateRuleDto.java
  src/main/java/com/dku/council/domain/post/model/dto/response/ResponseSingleGenericPostDto.java
  src/main/java/com/dku/council/domain/post/model/entity/Post.java
  src/main/java/com/dku/council/domain/post/model/entity/posttype/Conference.java
  src/main/java/com/dku/council/domain/post/model/entity/posttype/GeneralForum.java
  src/main/java/com/dku/council/domain/post/model/entity/posttype/News.java
  src/main/java/com/dku/council/domain/post/model/entity/posttype/Petition.java
  src/main/java/com/dku/council/domain/post/model/entity/posttype/Rule.java
  src/main/java/com/dku/council/domain/post/service/GenericPostService.java
  src/main/java/com/dku/council/global/dto/ResponseIdDto.java
  src/main/java/com/dku/council/global/dto/ResponseSuccessDto.java
  src/main/java/com/dku/council/global/interceptor/VoidSuccessResponseInterceptor.java
  src/main/resources/errors.properties
  src/test/java/com/dku/council/domain/category/service/CategoryServiceTest.java
  src/test/java/com/dku/council/domain/comment/service/CommentServiceTest.java
  src/test/java/com/dku/council/domain/post/controller/NewsControllerTest.java
  src/test/java/com/dku/council/domain/post/service/GenericPostServiceTest.java
  src/test/java/com/dku/council/global/interceptor/VoidSuccessResponseInterceptorTest.java
  src/test/java/com/dku/council/mock/CategoryMock.java
  src/test/java/com/dku/council/mock/CommentMock.java
  src/test/java/com/dku/council/mock/RandomGen.java
  src/test/resources/errors.properties
Labels: deploy
